### PR TITLE
Blog - fix some typos in old tutorials and invalid links

### PR DESCRIPTION
**Pull request by szyrom**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/78)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @szyrom)

---

*[_posts/2015-06-15-transactions.md, line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/78#-LEt7nSY57MSPaHabhMe:-LEt7nSY57MSPaHabhMf:b-9i8za7) ([raw file](https://github.com/pmem/pmem.github.io/blob/449582a3c02b129b9dcb5418ed2d58667aa283e4/_posts/2015-06-15-transactions.md#L16)):*
> ```Markdown
> lifecycle
> 
> You can see here how to use each of the stage-managing functions. The `pmemobj_tx_process` function can be used **instead** of others to move the transaction forward - you can call it if you don't know in which stage you are currently in. All of this can get fairly complicated, for more information please check out the [manpage](http://pmem.io/pmdk/manpages/linux/v1.0/libpmemobj.3.html). To avoid having to micro-manage this entire process the pmemobj library provides a set of macros that are built on top of these functions that greatly simplify using the transactions and this tutorial will exclusively use them.
> ```

I think we should link to the latest version (master).

---

*[_posts/2015-06-15-transactions.md, line 84 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/78#-LEtaxgS7Dr2bv9vdc9n:-LEtaxgUCYOkN3yY7XFl:b-7ropln) ([raw file](https://github.com/pmem/pmem.github.io/blob/449582a3c02b129b9dcb5418ed2d58667aa283e4/_posts/2015-06-15-transactions.md#L84)):*
> ```Markdown
> TX_STAGE_ONABORT/TX_STAGE_FINALLY needs to be volatile-qualified - otherwise you might
> encounter undefined behavior. Please see the CAVEATS section in libpmemobj
> [manpage](http://pmem.io/pmdk/manpages/linux/v1.0/libpmemobj.3.html) for more information.
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/78)*

**Comment by szyrom** [comment]
Review status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @szyrom)

---

*[_posts/2015-06-15-transactions.md, line 84 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/78#-LEtaxgS7Dr2bv9vdc9n:-LEtc2M_EuKOnC3tdu66:bex5yb4) ([raw file](https://github.com/pmem/pmem.github.io/blob/449582a3c02b129b9dcb5418ed2d58667aa283e4/_posts/2015-06-15-transactions.md#L84)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

I thought so, but 1) master version of man does not include CACEATS section 2) blog post was written when old pmemlibobj version was valid

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/78)*

**Comment by marcinslusarz** [comment]
Review status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @szyrom and @marcinslusarz)

---

*[_posts/2015-06-15-transactions.md, line 84 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/78#-LEtaxgS7Dr2bv9vdc9n:-LEtgXmj3d8w57Et2TtT:b-yeiuu0) ([raw file](https://github.com/pmem/pmem.github.io/blob/449582a3c02b129b9dcb5418ed2d58667aa283e4/_posts/2015-06-15-transactions.md#L84)):*
<details><summary><i>Previously, szyrom (szyrom) wrote…</i></summary><blockquote>

I thought so, but 1) master version of man does not include CACEATS section 2) blog post was written when old pmemlibobj version was valid
</blockquote></details>

1) http://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_tx_begin.3#caveats
2) this is still valid

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/78)*

**Comment by krzycz** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @szyrom)

---

*[_posts/2015-06-15-transactions.md, line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/78#-LEt7nSY57MSPaHabhMe:-LEyTu8SCYMhAa8HD0SK:b-8fx2u7) ([raw file](https://github.com/pmem/pmem.github.io/blob/449582a3c02b129b9dcb5418ed2d58667aa283e4/_posts/2015-06-15-transactions.md#L16)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

I think we should link to the latest version (master).
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/78)*

**Comment by szyrom** [comment]
Review status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @krzycz and @marcinslusarz)

---

*[_posts/2015-06-15-transactions.md, line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/78#-LEt7nSY57MSPaHabhMe:-LF1WJJb2j16hKckXyTa:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/449582a3c02b129b9dcb5418ed2d58667aa283e4/_posts/2015-06-15-transactions.md#L16)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.

---

*[_posts/2015-06-15-transactions.md, line 84 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/78#-LEtaxgS7Dr2bv9vdc9n:-LF1WMfM9WbcYk_zmH3I:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/449582a3c02b129b9dcb5418ed2d58667aa283e4/_posts/2015-06-15-transactions.md#L84)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

1) http://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_tx_begin.3#caveats
2) this is still valid
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/78)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/78#-:-LF2-tfV2KIM014BtO4Y:bnfp4nl)*

**Pull request merged**
