### PR TITLE
rpma: change format of links to the MD one

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/217)

### CODE REVIEW

**Comment by ldorau** [comment]
@lukaszstolarczuk

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/217)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau and @lukaszstolarczuk)

___
*[content/rpma/_index.md, line 12 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/217#-MxiwaR227ouZnNEd5U0:-MxiwaR227ouZnNEd5U1:bo0f5i0) ([raw file](https://github.com/pmem/pmem.github.io/blob/f16df745eb496b191d51b19ffe712fb7b010574f/content/rpma/_index.md#L12)):*
> ```Markdown
> # Description
> description: ""
> disclaimer: "The contents of this web site and the associated <a href=\"https://github.com/pmem\">GitHub repositories</a> are BSD-licensed open source."
> ```

FYI, this one I'd leave as is - it's a part of the template
___
*[content/rpma/_index.md, line 34 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/217#-MxiwW8NA67S8yv5aqFL:-MxiwW8OEcjBwlcnk9o3:b3kqx) ([raw file](https://github.com/pmem/pmem.github.io/blob/f16df745eb496b191d51b19ffe712fb7b010574f/content/rpma/_index.md#L34)):*
> ```Markdown
> * [Performance - Tuning](/rpma/documentation/perf-tuning)
> 
> ### <a href="/rpma/reports">Performance reports</a>
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/217)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[content/rpma/_index.md, line 34 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/217#-MxiwW8NA67S8yv5aqFL:-MxiyRRR9vacKwTtNpqL:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/f16df745eb496b191d51b19ffe712fb7b010574f/content/rpma/_index.md#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:+1: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/217#-:-Mxj15Ed-5qn4A-2OFq3:b-8fx2u7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
