### PR TITLE
rpma: update perf-tuning.md for ICX

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224#-:-MyS9tZq8PQaDs18Zu8p:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MyfWU2D60ubOMbb8Lgy:-MyfWU2D60ubOMbb8Lgz:b150qkg) (no related file):*
I think now it would be better to have all "Cascade Lake" (and "Ice Lake" too) settings merged together.
@grom72 what do you think ?

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MyfWU2D60ubOMbb8Lgy:-Myglc9z7TFJKuC1L6GG:bejn870) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau good point (and only differences marked separately)
</blockquote></details>

@osalyk perhaps a solution would be to add a suffix (Ice Lake only/ Cascade Lake only) for platform-specific knobs

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MyfWU2D60ubOMbb8Lgy:-Mygo-f4C63Uy3Fca1eW:b-b3cyja) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@osalyk perhaps a solution would be to add a suffix (Ice Lake only/ Cascade Lake only) for platform-specific knobs
</blockquote></details>

@grom72  I meant something different - to merge together all "Cascade Lake" settings and all "Ice Lake" settings but each of them separately - it would be much easier to read and use.

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MyfWU2D60ubOMbb8Lgy:-Mygp1Pk6T_C43TaqiYX:bno3lkp) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72  I meant something different - to merge together all "Cascade Lake" settings and all "Ice Lake" settings but each of them separately - it would be much easier to read and use.
</blockquote></details>

Works for me also.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MyfWU2D60ubOMbb8Lgy:-Mygz2U20QOKuJ8HQyO7:b-ueemtn) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Works for me also.
</blockquote></details>

OK, so @osalyk let's do it.

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MyfWU2D60ubOMbb8Lgy:-MykMYv7EWXmeEwqWPy9:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, so @osalyk let's do it.
</blockquote></details>

Done.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[content/rpma/documentation/perf-tuning.md, line 59 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MykP2DK27E8kWpUKQ2J:-MykP2DK27E8kWpUKQ2K:b4ei9ej) ([raw file](https://github.com/pmem/pmem.github.io/blob/5fc4bbb193e0156f5eff1a718bac02f91b7ac89b/content/rpma/documentation/perf-tuning.md#L59)):*
> ```Markdown
> ### Ice Lake
> 
> * Platform and CPU related [[1.1]][opt-part-1]
> ```

All such references (`[[1.1]][opt-part-1]`) do not work:





_Code quote:_
```Markdown
[[1.1]][opt-part-1]
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[content/rpma/documentation/perf-tuning.md, line 59 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MykP2DK27E8kWpUKQ2J:-MykQp4nDvQpj9UrGreP:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/5fc4bbb193e0156f5eff1a718bac02f91b7ac89b/content/rpma/documentation/perf-tuning.md#L59)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

All such references (`[[1.1]][opt-part-1]`) do not work:



</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[content/rpma/documentation/perf-tuning.md, line 59 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MykcpHtC7o6eA0e8yOS:-MykcpHtC7o6eA0e8yOT:bjsnsxl) ([raw file](https://github.com/pmem/pmem.github.io/blob/2a178024a3ace345147ec99eca5d1b110de5de3e/content/rpma/documentation/perf-tuning.md#L59)):*
> ```Markdown
> ### Ice Lake
> 
> * Platform and CPU related <a href="https://software.intel.com/content/www/us/en/develop/articles/optimizing-computer-applications-for-latency-part-1-configuring-the-hardware.html">[1.1]</a>
> ```

1) Use references to not repeat usage of the same URLs and
2) use MD-style links, please.



_Code quote:_
```Markdown
<a href="https://software.intel.com/content/www/us/en/develop/articles/optimizing-computer-applications-for-latency-part-1-configuring-the-hardware.html">[1.1]</a>
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[content/rpma/documentation/perf-tuning.md, line 80 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MykrE7P9_mD0DBTFIic:-MykrE7P9_mD0DBTFIid:b-hrwpp8) ([raw file](https://github.com/pmem/pmem.github.io/blob/5fc4bbb193e0156f5eff1a718bac02f91b7ac89b/content/rpma/documentation/perf-tuning.md#L80)):*
> ```Markdown
> * Disable Hardware Power Management, introduced in the Intel® Xeon® processor E5-2600 v4 product family. It provides more control over power management, but it can cause jitter and so is not recommended for latency-sensitive applications.
>     * Advanced Power Management Configuration - - CPU P State Control - Energy Efficient Turbo - **Disable**
>     * Advanced Power Management Configuration - - CPU P State Control - - Turbo Mode - **Disable**
> ```

Why 2 dashes?
` - - `



_Code quote:_
```Markdown
 - - 
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[content/rpma/documentation/perf-tuning.md, line 80 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MykrE7P9_mD0DBTFIic:-MyksfUY2M-jqbowInAO:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/5fc4bbb193e0156f5eff1a718bac02f91b7ac89b/content/rpma/documentation/perf-tuning.md#L80)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why 2 dashes?
` - - `
</blockquote></details>

Done.
___
*[content/rpma/documentation/perf-tuning.md, line 59 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MykcpHtC7o6eA0e8yOS:-Myksh66DhQtVoT6oHRQ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/2a178024a3ace345147ec99eca5d1b110de5de3e/content/rpma/documentation/perf-tuning.md#L59)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) Use references to not repeat usage of the same URLs and
2) use MD-style links, please.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[content/rpma/documentation/perf-tuning.md, line 59 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MykcpHtC7o6eA0e8yOS:-MykxnFuE2RdMFYqEnZw:bihzz94) ([raw file](https://github.com/pmem/pmem.github.io/blob/2a178024a3ace345147ec99eca5d1b110de5de3e/content/rpma/documentation/perf-tuning.md#L59)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet - the same URLs are still used many times.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[content/rpma/documentation/perf-tuning.md, line 59 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MykcpHtC7o6eA0e8yOS:-MylRJ5v1p5O-9JjkIWu:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/2a178024a3ace345147ec99eca5d1b110de5de3e/content/rpma/documentation/perf-tuning.md#L59)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet - the same URLs are still used many times.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[content/rpma/documentation/perf-tuning.md, line 90 at r5](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MylaFQW5DIEFHgh4jvA:-MylaFQW5DIEFHgh4jvB:bh844bs) ([raw file](https://github.com/pmem/pmem.github.io/blob/2b59f7ed2ed979acbfe8c460fa39a132653288bf/content/rpma/documentation/perf-tuning.md#L90)):*
> ```Markdown
> 
> [optimizing-computer]: https://software.intel.com/content/www/us/en/develop/articles/optimizing-computer-applications-for-latency-part-1-configuring-the-hardware.html
> [managment-states]: https://software.intel.com/content/www/us/en/develop/articles/power-management-states-p-states-c-states-and-package-c-states.html
> ```

managEment



_Code quote:_
```Markdown
managment
```
___
*[content/rpma/documentation/perf-tuning.md, line 91 at r5](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MylaKnw2IwjmA7ZXqwW:-MylaKnw2IwjmA7ZXqwX:b-f2mtvo) ([raw file](https://github.com/pmem/pmem.github.io/blob/2b59f7ed2ed979acbfe8c460fa39a132653288bf/content/rpma/documentation/perf-tuning.md#L91)):*
> ```Markdown
> [optimizing-computer]: https://software.intel.com/content/www/us/en/develop/articles/optimizing-computer-applications-for-latency-part-1-configuring-the-hardware.html
> [managment-states]: https://software.intel.com/content/www/us/en/develop/articles/power-management-states-p-states-c-states-and-package-c-states.html
> [persisten-memory]: https://www.intel.com/content/www/us/en/products/docs/memory-storage/optane-persistent-memory/optane-persistent-memory-200-series-brief.html
> ```

persistenT



_Code quote:_
```Markdown
persisten
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[content/rpma/documentation/perf-tuning.md, line 90 at r5](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MylaFQW5DIEFHgh4jvA:-MylbCARB28nbqDo2n50:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/2b59f7ed2ed979acbfe8c460fa39a132653288bf/content/rpma/documentation/perf-tuning.md#L90)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

managEment
</blockquote></details>

Done.
___
*[content/rpma/documentation/perf-tuning.md, line 91 at r5](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MylaKnw2IwjmA7ZXqwW:-MylbGmI6GgUnXrQ_V87:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/2b59f7ed2ed979acbfe8c460fa39a132653288bf/content/rpma/documentation/perf-tuning.md#L91)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

persistenT
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[content/rpma/documentation/perf-tuning.md, line 28 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MylcID9B3MJjY_U-H4H:-MylcID9B3MJjY_U-H4I:bwbzv09) ([raw file](https://github.com/pmem/pmem.github.io/blob/9812415a26b71e645eaec278a9cfa4f4a6ec6cb1/content/rpma/documentation/perf-tuning.md#L28)):*
> ```Markdown
> * Platform and CPU related [[1.1]][optimizing-computer]
>     * Disable lower CPU power states: C-states [[1.2]][manage
> ment-states], C1E, and memory and PCI-e power saving states. Settings vary from vendor to vendor so some of them may not be available for you e.g.:
> ```

What happened here? (broken line)



_Code quote:_
```Markdown
    * Disable lower CPU power states: C-states [[1.2]][manage
ment-states], C1E, and memory and PCI-e power saving states. Settings vary from vendor to vendor so some of them may not be available for you e.g.:
```
___
*[content/rpma/documentation/perf-tuning.md, line 62 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/224#-MyldGBH7LmMwEU33R18:-MyldGBH7LmMwEU33R19:b3kqx) ([raw file](https://github.com/pmem/pmem.github.io/blob/9812415a26b71e645eaec278a9cfa4f4a6ec6cb1/content/rpma/documentation/perf-tuning.md#L62)):*
> ```Markdown
> * Platform and CPU related [[1.1]][optimizing-computer]
>     * Disable lower CPU power states: C-states [[1.2]][manage
> ment-states] and memory and PCI-e power saving states. Settings vary from vendor to vendor so some of them may not be available for you e.g.:
> ```

.



_Code quote:_
```Markdown
    * Disable lower CPU power states: C-states [[1.2]][manage
ment-states] and memory and PCI-e power saving states. Settings vary from vendor to vendor so some of them may not be available for you e.g.:
```

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
