### PR TITLE
doc: rpma discontinuation announcement

### PR DESCRIPTION
**Pull request by grom72**
Preview:
https://grom72.github.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/378)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/378)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @janekmi and @osalyk)

___
*[`content/blog/2022/update-pmdk-project-status.md` line 114 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/378#-Nd_gNWK2ViGtxLDYFKD:-Nd_oOlL8NX0zKcGPjKm:bb77ufg) ([raw file](https://github.com/pmem/pmem.github.io/blob/76d0b4e533df61c49916af57ee8c97946c14eacc/content/blog/2022/update-pmdk-project-status.md#L114)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Should we consider mentioning this update took place? Otherwise, it is hard to notice.
</blockquote></details>

Yes.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/378#-:-NdbeRAwBAlb3nV0-AyQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/378#-:-NddHrMl4edKsWz9OCd7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/378)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
