### PR TITLE
rpma: update pmem.io benchmarking manuals for ICX and CLX DDIO

### PR DESCRIPTION
**Pull request by grom72**
Move common part to DDIO description to common paragraph

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/232)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/232)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/232)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[content/rpma/documentation/basic-direct-write-to-pmem.md, line 18 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/232#-N-Y8Iwl26ekwasSazdS:-N-Y8IwmEy2AZ7RNh8lI:b-oyikbf) ([raw file](https://github.com/pmem/pmem.github.io/blob/ab31050b89687c44e328186113b21200165a1451/content/rpma/documentation/basic-direct-write-to-pmem.md#L18)):*
> ```Markdown
> *Direct Write to PMem* is a readiness of hardware and software configuration which allows effectively and persistently write data to PMem physically attached to one system from another system using RDMA-capable network. How to achieve *Direct Write to PMem* capability may differ from system to system because of variety of potential 'interruptions' (e.g. caching) in data's way to be stored persistently on PMem.
> 
> For the 2nd and the 3rd Generation Intel&reg; Xeon&reg; Scalable Processors (**Ice Lake**) the only configuration item one should take care of is Intel&reg; Data Direct I/O Technology (**DDIO**). **DDIO** assumes the good enough place to effectively store data coming from the RDMA (and any other DMA traffic) is the CPU LLC from which CPU can access it more easily than when it would be stored in DRAM or on PMem [[1]][ddio]. This is beneficial for any other DMA traffic but prevents from achieving *Direct Write to PMem*.
> ```

`For the 2nd and the 3rd G...`
so
`(**Cascade Lake** and **Ice Lake**)` 
?



_Code quote:_
```Markdown
(**Ice Lake**)
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/232)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[content/rpma/documentation/basic-direct-write-to-pmem.md, line 18 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/232#-N-Y8Iwl26ekwasSazdS:-N-Y9RL5DUK2To5JfG4I:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/ab31050b89687c44e328186113b21200165a1451/content/rpma/documentation/basic-direct-write-to-pmem.md#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`For the 2nd and the 3rd G...`
so
`(**Cascade Lake** and **Ice Lake**)` 
?
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/232)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/232)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/232#-:-N-YBtDe4VLvv2g8nW_c:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/232#-:-N-YH7mv5COn3mt0fBOV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/232)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Comment by ldorau** [comment]
@osalyk Could you make the same PR for man-pages?

**Comment by osalyk** [comment]
> @osalyk Could you make the same PR for man-pages?

[#1660](https://github.com/pmem/rpma/pull/1660)

**Pull request merged**
