### PR TITLE
Add Cloudera Kudu Blog Post

### PR DESCRIPTION
**Pull request by sarahjelinek**
Blog post on Cloudera KUDU NVML integration.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/62)

### CODE REVIEW

**Comment by toddlipcon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md, line 8 at r1](https://reviewable.io:443/reviews/pmem/pmem.github.io/62#-KibN3XXkJD9E0O_QNLK:-KibN3XXkJD9E0O_QNLL:b-894ljp) ([raw file](https://github.com/pmem/pmem.github.io/blob/34fbfd4ac36e2b45e0aab35744af79a35c1135ed/_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md#L8)):*
> ```Markdown
> ---
> 
> # Using NVM Libraries To Add Persistent Memory Support to Cloudera Kudu Block Cache
> ```

"Apache Kudu" rather than "Cloudera Kudu"

---

*[_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md, line 13 at r1](https://reviewable.io:443/reviews/pmem/pmem.github.io/62#-KibNGTeXDkN30XaYqK-:-KibNGTeXDkN30XaYqK0:b-n2erar) ([raw file](https://github.com/pmem/pmem.github.io/blob/34fbfd4ac36e2b45e0aab35744af79a35c1135ed/_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md#L13)):*
> ```Markdown
> 
> Cloudera Kudu:
> https://github.com/cloudera/kudu
> ```

same here - Apache Kudu, and use http://github.com/apache/kudu or http://kudu.apache.org/

---

*[_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md, line 18 at r1](https://reviewable.io:443/reviews/pmem/pmem.github.io/62#-KibNMS_MnksJL_RneJd:-KibNMS_MnksJL_RneJe:bisuy1) ([raw file](https://github.com/pmem/pmem.github.io/blob/34fbfd4ac36e2b45e0aab35744af79a35c1135ed/_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md#L18)):*
> integration from Cloudera.
same - just say "official integration" - Cloudera isn't the steward of the project anymore

---

*[_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md, line 54 at r1](https://reviewable.io:443/reviews/pmem/pmem.github.io/62#-KibNckwIZbJ87KCzt7t:-KibNckwIZbJ87KCzt7u:bak0mac) ([raw file](https://github.com/pmem/pmem.github.io/blob/34fbfd4ac36e2b45e0aab35744af79a35c1135ed/_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md#L54)):*
> developed by Cloudera (www.cloudera.com)
same comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/62)*

**Comment by sarahjelinek** [comment]
*[_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md, line 13 at r1](https://reviewable.io:443/reviews/pmem/pmem.github.io/62#-KibNGTeXDkN30XaYqK-:-Kic6z5Y348QuCHnRdcF:bt2vr1b) ([raw file](https://github.com/pmem/pmem.github.io/blob/34fbfd4ac36e2b45e0aab35744af79a35c1135ed/_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md#L13)):*
<details><summary><i>Previously, toddlipcon (Todd Lipcon) wrote…</i></summary><blockquote>

same here - Apache Kudu, and use http://github.com/apache/kudu or http://kudu.apache.org/
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/62)*

**Comment by sarahjelinek** [comment]
*[_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md, line 8 at r1](https://reviewable.io:443/reviews/pmem/pmem.github.io/62#-KibN3XXkJD9E0O_QNLK:-Kic6yAZ31SqPEwAWVuy:bt2vr1b) ([raw file](https://github.com/pmem/pmem.github.io/blob/34fbfd4ac36e2b45e0aab35744af79a35c1135ed/_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md#L8)):*
<details><summary><i>Previously, toddlipcon (Todd Lipcon) wrote…</i></summary><blockquote>

"Apache Kudu" rather than "Cloudera Kudu"
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/62)*

**Comment by sarahjelinek** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md, line 18 at r1](https://reviewable.io:443/reviews/pmem/pmem.github.io/62#-KibNMS_MnksJL_RneJd:-Kic71-0uqhwi0p9vkQq:bt2vr1b) ([raw file](https://github.com/pmem/pmem.github.io/blob/34fbfd4ac36e2b45e0aab35744af79a35c1135ed/_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md#L18)):*
<details><summary><i>Previously, toddlipcon (Todd Lipcon) wrote…</i></summary><blockquote>

> integration from Cloudera.
same - just say "official integration" - Cloudera isn't the steward of the project anymore
</blockquote></details>

Fixed.

---

*[_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md, line 54 at r1](https://reviewable.io:443/reviews/pmem/pmem.github.io/62#-KibNckwIZbJ87KCzt7t:-Kic72GKyuNR3lOfP9wy:bt2vr1b) ([raw file](https://github.com/pmem/pmem.github.io/blob/34fbfd4ac36e2b45e0aab35744af79a35c1135ed/_posts/2017-04-03-cloudera-kudu-pmem-enabled-block-cache.md#L54)):*
<details><summary><i>Previously, toddlipcon (Todd Lipcon) wrote…</i></summary><blockquote>

> developed by Cloudera (www.cloudera.com)
same comment
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/62)*

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1.
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/62#-:-KiqRbsF9vVw7LDYaFBL:bnfp4nl)*

**Pull request merged**
