### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
The biggest one is to update CONTRIBUTING.md with up-to-date info.

// Preview:
https://lukaszstolarczuk.github.io/blog/2021/10/how-to-contribute-to-pmem.io/
https://github.com/lukaszstolarczuk/lukaszstolarczuk.github.io/blob/updates/CONTRIBUTING.md
https://lukaszstolarczuk.github.io/blog/2021/09/concurrency-considerations-in-libpmemobj-cpp/ ([before](https://pmem.io/blog/2021/09/concurrency-considerations-in-libpmemobj-cpp))

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/285)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/285)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[`CONTRIBUTING.md` line 89 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/285#-N7ujnCR4__goAIy0Qng:-N7ujnCR4__goAIy0Qnh:bu56gut) ([raw file](https://github.com/pmem/pmem.github.io/blob/4e1477e09c1058950930c89ec0d387e8d58fa1d6/CONTRIBUTING.md#L89)):*
> ```Markdown
> Make your changes to the file(s) you'd like to update.
> 
> Learn the structure of this repository and what file(s) should be modified and where to create new content, below.
> ```

a new content



_Code quote:_
```Markdown
new content
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/285)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @igchor and @ldorau)

___
*[`CONTRIBUTING.md` line 89 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/285#-N7ujnCR4__goAIy0Qng:-N7uqjyyAYvWQ0StJ9Fq:bn74dlv) ([raw file](https://github.com/pmem/pmem.github.io/blob/4e1477e09c1058950930c89ec0d387e8d58fa1d6/CONTRIBUTING.md#L89)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

a new content
</blockquote></details>

I checked this sentence with Grammarly and it proposed to leave it just as `new content` (with some other updates).

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/285)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @igchor)

___
*[`CONTRIBUTING.md` line 89 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/285#-N7ujnCR4__goAIy0Qng:-N7wNPBmDbL3aLM-j3-f:b32w0x) ([raw file](https://github.com/pmem/pmem.github.io/blob/4e1477e09c1058950930c89ec0d387e8d58fa1d6/CONTRIBUTING.md#L89)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I checked this sentence with Grammarly and it proposed to leave it just as `new content` (with some other updates).
</blockquote></details>

OK

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/285#-:-N88igrB5Uv1RpIVKkQp:bnfp4nl)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
