### PR TITLE
cpp: transactions blog entry

### PR DESCRIPTION
**Pull request by tomaszkapela**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/42)

### CODE REVIEW

**Comment by krzycz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2016-05-25-cpp-07.md, line 107 \[r1\]](https://reviewable.io:443/reviews/pmem/pmem.github.io/42#-KJaLHNmR5vkQLioS38R:-KJaLHNmR5vkQLioS38S:1348925264) ([raw file](https://github.com/pmem/pmem.github.io/blob/3d4d75dbdbca7765c4d2716983a8c838905c0391/_posts/2016-05-25-cpp-07.md#L107)):*
> ```Markdown
> `std::uncaught_exceptions` from C++17, which is available if the
> `__cpp_lib_uncaught_exceptions` feature test macro is defined. It is available
> since GCC 6.1(libstdc++) and clang 3.7(libc++). The utomatic version releases
> ```

utomatic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/42)*

**Comment by tomaszkapela** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2016-05-25-cpp-07.md, line 107 \[r1\]](https://reviewable.io:443/reviews/pmem/pmem.github.io/42#-KJaLHNmR5vkQLioS38R:-KJaNE2hkDSVkfr9ljNg:-499146009) ([raw file](https://github.com/pmem/pmem.github.io/blob/3d4d75dbdbca7765c4d2716983a8c838905c0391/_posts/2016-05-25-cpp-07.md#L107)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary>
> utomatic?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/42)*

**Comment by krzycz** [comment]
:lgtm:

<details><summary><i>Previously, tomaszkapela wrote…</i></summary>
> #### cpp: transactions blog entry
</details>


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/42#-:-KJaPXAlt-2OW2TdSDnz:1417088721)*

**Comment by marcinslusarz** [comment]
*[_posts/2016-05-25-cpp-07.md, line 40 \[r2\]](https://reviewable.io:443/reviews/pmem/pmem.github.io/42#-KJaPhcACbs7_AsfM1au:-KJaPhcACbs7_AsfM1av:160407176) ([raw file](https://github.com/pmem/pmem.github.io/blob/f8b44ed6d169b85b312e9c8ba97a739eadcab5bd/_posts/2016-05-25-cpp-07.md#L40)):*
> ```Markdown
> {% highlight cpp linenos %}
> auto pop = pool_base::create(...);
> transaction::exec_tx(pop, transaction_fx, locks...);
> ```

fx?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/42)*

**Pull request merged**
