### PR TITLE
add disaggregated memory post

### PR DESCRIPTION
**Pull request by pbalcer**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/194)

### CODE REVIEW

**Comment by pbalcer** [comment]
Preview: https://pbalcer.github.io/blog/2022/01/disaggregated-memory-in-pursuit-of-scale-and-efficiency/

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/194)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @kilobyte and @pbalcer)

___
*[content/blog/2022/cxl.md, line 81 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtrHY03EkzqD_f2rwC1:-MtrHY03EkzqD_f2rwC2:b-lsh1np) ([raw file](https://github.com/pmem/pmem.github.io/blob/a64e7ea51956d8dd22855bca79bf30d28a45035f/content/blog/2022/cxl.md#L81)):*
> ```Markdown
> For many, locally attached storage has become a cache.
> 
> So, M3 (Magnificent Memory Manager?) anyone? But is moving memory outside of the
> ```

It's unobvious to me what M3 is.  Is it something that already exists?  If so, there should be a link.  Is it a name you just invented?  If so, it should be introduced somehow.
___
*[content/blog/2022/cxl.md, line 171 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtrIq2GAP0tvMfkMNNu:-MtrIq2GAP0tvMfkMNNv:b-wp9d9w) ([raw file](https://github.com/pmem/pmem.github.io/blob/a64e7ea51956d8dd22855bca79bf30d28a45035f/content/blog/2022/cxl.md#L171)):*
> ```Markdown
> 
> Armed with this knowledge, software should then be able to make informed data
> placement decisions - which memory allocations go where.
> ```

The grammar of the latter clause sounds unwieldy to me.

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/194)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @kilobyte)

___
*[content/blog/2022/cxl.md, line 81 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtrHY03EkzqD_f2rwC1:-MtrJRcr8QVe_u5iExiS:b-dzn6hz) ([raw file](https://github.com/pmem/pmem.github.io/blob/a64e7ea51956d8dd22855bca79bf30d28a45035f/content/blog/2022/cxl.md#L81)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

It's unobvious to me what M3 is.  Is it something that already exists?  If so, there should be a link.  Is it a name you just invented?  If so, it should be introduced somehow.
</blockquote></details>

M3 is a reference to S3 - Simple Storage Service from AWS. The previous paragraph talked about storage services like S3, so here I wanted to 'invent' a similar acronym for an imaginary memory service.
___
*[content/blog/2022/cxl.md, line 171 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtrIq2GAP0tvMfkMNNu:-MtrJlfMEaJ0417_9hFG:bsqvn4e) ([raw file](https://github.com/pmem/pmem.github.io/blob/a64e7ea51956d8dd22855bca79bf30d28a45035f/content/blog/2022/cxl.md#L171)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

The grammar of the latter clause sounds unwieldy to me.
</blockquote></details>

I agree. I've noticed this before, but I'm not sure how to change it to something better. I'll think about it, but any suggestions are welcome :)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/194)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @igchor, @kilobyte, and @pbalcer)

___
*[content/blog/2022/cxl.md, line 155 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtsJWURAGGN_RBbCiux:-MtsJWURAGGN_RBbCiuy:b9w52n4) ([raw file](https://github.com/pmem/pmem.github.io/blob/a64e7ea51956d8dd22855bca79bf30d28a45035f/content/blog/2022/cxl.md#L155)):*
> ```Markdown
> CXL hierarchy
> 
> Given that there might be many types of different memory in a system, there
> ```

nit: 'many different types of memory'?
___
*[content/blog/2022/cxl.md, line 176 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtsIpzYEJezasei1HVJ:-MtsIpzZ6KJIBlrsM554:bp3cplm) ([raw file](https://github.com/pmem/pmem.github.io/blob/a64e7ea51956d8dd22855bca79bf30d28a45035f/content/blog/2022/cxl.md#L176)):*
> ```Markdown
> 
> And to the extent that transparent data placement is possible, I agree.
> But there to some caveats, in my opinion.
> ```

to -> are?

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/194)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @igchor and @kilobyte)

___
*[content/blog/2022/cxl.md, line 155 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtsJWURAGGN_RBbCiux:-MtsMmd2DsDrIPx--Ixg:bb7f2mf) ([raw file](https://github.com/pmem/pmem.github.io/blob/a64e7ea51956d8dd22855bca79bf30d28a45035f/content/blog/2022/cxl.md#L155)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: 'many different types of memory'?
</blockquote></details>

done
___
*[content/blog/2022/cxl.md, line 176 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtsIpzYEJezasei1HVJ:-MtsMoRXB5XiHwwA9-2l:bb7f2mf) ([raw file](https://github.com/pmem/pmem.github.io/blob/a64e7ea51956d8dd22855bca79bf30d28a45035f/content/blog/2022/cxl.md#L176)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

to -> are?
</blockquote></details>

done

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/194)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @igchor and @kilobyte)

___
*[content/blog/2022/cxl.md, line 171 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtrIq2GAP0tvMfkMNNu:-MtsMwB02klpmoo9b5t3:b-v4jnzb) ([raw file](https://github.com/pmem/pmem.github.io/blob/a64e7ea51956d8dd22855bca79bf30d28a45035f/content/blog/2022/cxl.md#L171)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I agree. I've noticed this before, but I'm not sure how to change it to something better. I'll think about it, but any suggestions are welcome :)
</blockquote></details>

I changed this to `Armed with this knowledge, software should then be able to make informed data placement decisions about which allocations go to which memory`.

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/194)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @igchor, @kilobyte, @PatKamin, and @pbalcer)

___
*[content/blog/2022/cxl.md, line 55 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtvhQzt6JyRNxWdsg53:-MtvhQzt6JyRNxWdsg54:bk8wbry) ([raw file](https://github.com/pmem/pmem.github.io/blob/e313efd0c8ae0eb0c31e1c78efe36ac1f1a0c758/content/blog/2022/cxl.md#L55)):*
> ```Markdown
> increasingly difficult for CSPs and hardware vendors to provide sufficient
> memory capacity and bandwidth per CPU core. And there are only so many memory
> channels you can add to a sever before you physically run out of space on the
> ```

sever -> server

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/194)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @igchor, @kilobyte, @PatKamin, and @pbalcer)

___
*[content/blog/2022/cxl.md, line 81 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtrHY03EkzqD_f2rwC1:-Mtw4Fjf68dZb5dDqmbo:b-p4b4o4) ([raw file](https://github.com/pmem/pmem.github.io/blob/a64e7ea51956d8dd22855bca79bf30d28a45035f/content/blog/2022/cxl.md#L81)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

M3 is a reference to S3 - Simple Storage Service from AWS. The previous paragraph talked about storage services like S3, so here I wanted to 'invent' a similar acronym for an imaginary memory service.
</blockquote></details>

Right, I see.  It's just that an unobvious idiot may miss this (I'm glad to provide the idiocy service :) ).

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/194)* status: all files reviewed, 3 unresolved discussions (waiting on @pbalcer)

___
*[content/blog/2022/cxl.md, line 149 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtwEN22A1lp2IXk8ENP:-MtwEN22A1lp2IXk8ENQ:b7h17kl) ([raw file](https://github.com/pmem/pmem.github.io/blob/e313efd0c8ae0eb0c31e1c78efe36ac1f1a0c758/content/blog/2022/cxl.md#L149)):*
> ```Markdown
> In practice, the CXL.mem protocol expands the increasingly heterogeneous memory
> hierarchy of modern servers. The specific access latency of remote attached
> memory will dependent on the type of media used in the device.
> ```

will be / will depend

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/194)* status: all files reviewed, 3 unresolved discussions (waiting on @kilobyte, @lukaszstolarczuk, and @PatKamin)

___
*[content/blog/2022/cxl.md, line 81 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtrHY03EkzqD_f2rwC1:-MtwuPf19mDuq5qvIk40:b-eimgjw) ([raw file](https://github.com/pmem/pmem.github.io/blob/a64e7ea51956d8dd22855bca79bf30d28a45035f/content/blog/2022/cxl.md#L81)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Right, I see.  It's just that an unobvious idiot may miss this (I'm glad to provide the idiocy service :) ).
</blockquote></details>

I've added an explicit reference to S3 in the earlier paragraph. Hopefully, that addition will make this more obvious.
___
*[content/blog/2022/cxl.md, line 55 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtvhQzt6JyRNxWdsg53:-MtwtzN23-8yv-8433mS:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/e313efd0c8ae0eb0c31e1c78efe36ac1f1a0c758/content/blog/2022/cxl.md#L55)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

sever -> server
</blockquote></details>

Done.
___
*[content/blog/2022/cxl.md, line 149 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/194#-MtwEN22A1lp2IXk8ENP:-Mtwv5vvCtHtgtyk1nJZ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/e313efd0c8ae0eb0c31e1c78efe36ac1f1a0c758/content/blog/2022/cxl.md#L149)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

will be / will depend
</blockquote></details>

Done.

**Pull request merged**
