### PR TITLE
Add PMDK 2.0.0 announcement

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/366)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/366)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[`content/announcements/2023/PMDK-v2-0-0-release.md` line 36 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/366#-Nc7vzBE6Tpt1u5_YIWL:-Nc7vzBE6Tpt1u5_YIWM:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/3882cb0cd1154a3cfa80d4503c4d8cc047dd88b8/content/announcements/2023/PMDK-v2-0-0-release.md#L36)):*
> ```Markdown
> Removes:
> - support for Windows/FreeBSD,
> - libpmemlog and libpmemblk libraries.
> ```





_Suggestion:_
```Markdown
- libpmemlog and libpmemblk libraries,
- remove all experimental code (including pmem2_async).
```
___
*[`content/announcements/2023/PMDK-v2-0-0-release.md` line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/366#-Nc7vUuX7arJl4arBg_v:-Nc7vUuX7arJl4arBg_w:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/3882cb0cd1154a3cfa80d4503c4d8cc047dd88b8/content/announcements/2023/PMDK-v2-0-0-release.md#L38)):*
> ```Markdown
> - libpmemlog and libpmemblk libraries.
> 
> Significantly simplifies the validation by:
> ```





_Suggestion:_
```Markdown
Simplifies
```
___
*[`content/announcements/2023/PMDK-v2-0-0-release.md` line 41 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/366#-Nc7wqlQBmlb-Xi4Mek4:-Nc7wqlR4b_rgV8ASqA4:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/3882cb0cd1154a3cfa80d4503c4d8cc047dd88b8/content/announcements/2023/PMDK-v2-0-0-release.md#L41)):*
> ```Markdown
> - removing experimentally supported PowerPC and ARM architectures from the regular execution,
> - dropping Fedora and Debian,
> - adding reference platform provisioning instructions for the PMDK testing.
> ```





_Suggestion:_
```Markdown
- dropping Fedora and Debian.

Extend documentation by
- platform provisioning instructions for the PMDK testing (including ansible playbook examples).
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/366)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`content/announcements/2023/PMDK-v2-0-0-release.md` line 36 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/366#-Nc7vzBE6Tpt1u5_YIWL:-NcLwUrI5S8BWwpvHxWl:b-dhkst4) ([raw file](https://github.com/pmem/pmem.github.io/blob/3882cb0cd1154a3cfa80d4503c4d8cc047dd88b8/content/announcements/2023/PMDK-v2-0-0-release.md#L36)):*
> ```Markdown
> Removes:
> - support for Windows/FreeBSD,
> - libpmemlog and libpmemblk libraries.
> ```

"remove all experimental code" is not true. We still have other experimental supports: https://github.com/pmem/pmdk#experimental-supports

```
- libpmemlog and libpmemblk libraries,
- pmem2_async experimental functions.
```
___
*[`content/announcements/2023/PMDK-v2-0-0-release.md` line 41 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/366#-Nc7wqlQBmlb-Xi4Mek4:-NcLxWqp-GQee8TWskTR:bo0p0t0) ([raw file](https://github.com/pmem/pmem.github.io/blob/3882cb0cd1154a3cfa80d4503c4d8cc047dd88b8/content/announcements/2023/PMDK-v2-0-0-release.md#L41)):*
> ```Markdown
> - removing experimentally supported PowerPC and ARM architectures from the regular execution,
> - dropping Fedora and Debian,
> - adding reference platform provisioning instructions for the PMDK testing.
> ```

```
Extend the documentation by:
- Ansible playbook examples on platform provisioning instructions for the PMDK testing.
```

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/366)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/366)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Pull request merged**
