### PR TITLE
pmdk: add 1.13 tag in releases_*.yml

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/352)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/352)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/352)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`data/releases_linux.yml` line 435 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/352#-NU1Zqwc5d3zF-5tdm4U:-NU1Zqwc5d3zF-5tdm4V:b3kre) ([raw file](https://github.com/pmem/pmem.github.io/blob/d244b9860e15d47f5fca057de6f14c81fe2f782d/data/releases_linux.yml#L435)):*
> ```YAML
>     libpmempool
>     libpmemset
>     libvmem
> ```

?
___
*[`data/releases_linux.yml` line 797 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/352#-NU1_S7l3MQxP4t3kR8j:-NU1_S7l3MQxP4t3kR8k:b3kre) ([raw file](https://github.com/pmem/pmem.github.io/blob/d244b9860e15d47f5fca057de6f14c81fe2f782d/data/releases_linux.yml#L797)):*
> ```YAML
>         vmem_stats_print.3
>         vmem_strdup.3
>         vmem_wcsdup.3
> ```

?
___
*[`data/releases_windows.yml` line 415 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/352#-NU1_sl-CedlltL8TB3w:-NU1_sl-CedlltL8TB3x:b3kre) ([raw file](https://github.com/pmem/pmem.github.io/blob/d244b9860e15d47f5fca057de6f14c81fe2f782d/data/releases_windows.yml#L415)):*
> ```YAML
>     libpmemobj
>     libpmempool
>     libvmem
> ```

?
___
*[`data/releases_windows.yml` line 776 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/352#-NU1aeRzBkEPr_QnPyZ1:-NU1aeRzBkEPr_QnPyZ2:b3kre) ([raw file](https://github.com/pmem/pmem.github.io/blob/d244b9860e15d47f5fca057de6f14c81fe2f782d/data/releases_windows.yml#L776)):*
> ```YAML
>         vmem_stats_print.3
>         vmem_strdup.3
>         vmem_wcsdup.3
> ```

?

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/352)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by janekmi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/352)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
