### PR TITLE
pmdk: update librpmem information

### PR DESCRIPTION
**Pull request by wlemkows**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/229)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/229)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wlemkows)

**Review by lplewa — APPROVED** [review]

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/229#-:-N-SiY6-1la6-XN0FQSj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wlemkows)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/229)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wlemkows)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/229#-:-N-W_RjW8gXCXBuhwITy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wlemkows)

**Pull request merged**
