### PR TITLE
blog: add post describing Windows support

### PR DESCRIPTION
**Pull request by peluse**
this is my first attempt at submitting a blog entry so be gentile on me :)

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/52)

### CODE REVIEW

**Comment by lplewa** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2016-12-21-windows-nvml.md, line 56 at r1](https://reviewable.io:443/reviews/pmem/pmem.github.io/52#-KZa3hiDFVR7dZFTWPZX:-KZa3hiEQRus_JJq-6Ee:bd2j7vb) ([raw file](https://github.com/pmem/pmem.github.io/blob/ec57d59f2135a7de8961ea14000a3a08a20380f7/_posts/2016-12-21-windows-nvml.md#L56)):*
> ```Markdown
> 
> The Windows unit tests are executed automatically when a pull request
> is made, ReviewBoard is still used for reviews however AppVeyor controls
> ```

reviewable ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/52)*

**Comment by peluse** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2016-12-21-windows-nvml.md, line 56 at r1](https://reviewable.io:443/reviews/pmem/pmem.github.io/52#-KZa3hiDFVR7dZFTWPZX:-KZb5TGmu2Elz7KT_jbh:b-ucvmml) ([raw file](https://github.com/pmem/pmem.github.io/blob/ec57d59f2135a7de8961ea14000a3a08a20380f7/_posts/2016-12-21-windows-nvml.md#L56)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

reviewable ;)
</blockquote></details>

LOL, wrong project!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/52)*

**Comment by peluse** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2016-12-21-windows-nvml.md, line 56 at r1](https://reviewable.io:443/reviews/pmem/pmem.github.io/52#-KZa3hiDFVR7dZFTWPZX:-KZb5pY5ThXGJl80VIa8:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/ec57d59f2135a7de8961ea14000a3a08a20380f7/_posts/2016-12-21-windows-nvml.md#L56)):*
<details><summary><i>Previously, peluse (Paul Luse) wrote…</i></summary><blockquote>

LOL, wrong project!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/52)*

**Comment by andyrudoff** [comment]
This looks good.  My only comment is that it says the Tech Preview release is now available but doesn't provide a link to it (and going to the nvml tree and clicking on releases doesn't have any releases other than what we've done for Linux).  Is this blog entry meant to be posted immediately or after the Windows Tech Preview release is tagged?

**Comment by peluse** [comment]
Cool, thanks.  Yeah I figured based on the wording that Krzy would approve once the Windows release was done...

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/52#-:-KZhMS8Za8WixPIND5PS:b-wpnly)*

**Comment by krzycz** [comment]
Right. Tech Preview is not available yet. 
I'm going to merge this patch and make this blog article visible right after we tag the TP release. 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmem.github.io/52#-:-KZhb8WjHgCs95ZF6Kpn:b-n4ghh0)*

**Pull request merged**
