### PR TITLE
Escape Analysis in PMDK

### PR DESCRIPTION
**Pull request by lplewa**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/157)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/157)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @lplewa)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQdGEtDjBhD0IEC1xv:-MdQdGEtDjBhD0IEC1xw:b-uuio0o) (no related file):*
pls add a link to the preview of generated post

---
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 2 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQdW3j0NiCESdIJoip:-MdQdW3j0NiCESdIJoiq:buqc3s) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L2)):*
> ```
> ---
> title: Escape Analysis in PMDK
> ```

why uppercase E.A. ? I don't think it's a proper noun :wink:
(in the entire blog post)
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 3 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQbfi62aF6CA4mXQhN:-MdQbfi62aF6CA4mXQhO:b-uxtr8u) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L3)):*
> ```
> ---
> title: Escape Analysis in PMDK
> author: Łukasz Plewa
> ```

your gh login
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 5 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQbwQh09QAav10U9tn:-MdQbwQi59Ub0hiU6_3P:b-vhk4t8) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L5)):*
> ```
> author: Łukasz Plewa
> layout: post
> identifier: Escape_analiysis_H1_2021
> ```

1. `analysis`
2. usually lowercase
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 10 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQc9MJCvs92swmiihr:-MdQc9MJCvs92swmiihs:b35dvbn) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L10)):*
> ```
> ### Introduction
> 
> We believe that PMDK has a really good quality assurance process but there is always a place to improve.
> ```

pls run this whole thing with Grammarly or something, before posting :wink:
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 21 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQcobZ7VXTA0wHXL1Y:-MdQcobZ7VXTA0wHXL1Z:bdp3bh) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L21)):*
> ```
> 
> 
> ### How we do an Escape Analysis
> ```

`How do we do`
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQd0L9442ROTZ4q8uT:-MdQd0L9442ROTZ4q8uU:b-ykutla) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L38)):*
> ```
> 
> Two first bugs on our list are:
> [Make Check failed on Arm64][5255] and [pmempool_sync/TEST6 fails on ppc64le using device dax][5112]
> ```

put all these names of the issues in quotes or maybe add a **bold**
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 71 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQcOyi0S9-RlyYyrX_:-MdQcOyi0S9-RlyYyrXa:bsrtpme) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L71)):*
> ```
> 
> ```

pls fix all the random empty lines

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/157)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @lplewa)

___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 56 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdR60bd9Bo91GOO2Ll_:-MdR60bd9Bo91GOO2Lla:bs0yllt) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L56)):*
> ```
> 
> The only escape found in libpmemobj-cpp repository:
> XXX: Ask Igor to write few words about his issue
> ```

The only escape found in the libpmemobj-cpp repository is related to missing documentation for pmem::obj::transaction::manual class. This class is a wrapper around C transactions API from pmemobj. It's functionality is very similar to the C counterpart but it misses all the description (e.g. about transaction stages) which can be found in pmemobj manpages. This results in misuses of C++ API.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/157)* status: all files reviewed, 21 unresolved discussions (waiting on @lplewa)

___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 12 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRA_Bn74p2T-nb6H20:-MdRA_Bn74p2T-nb6H21:b-hon2w8) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L12)):*
> ```
> We believe that PMDK has a really good quality assurance process but there is always a place to improve.
> To try to find an area for improvement we decided to try a new process called Escape Analysis.
> Escape is a confirmed bug that was reported by someone who is not involved in PMDK development.
> ```

the PMDK
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRAaOI0gmOf9rFV1TA:-MdRAaOI0gmOf9rFV1TB:b-hon2w8) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L13)):*
> ```
> To try to find an area for improvement we decided to try a new process called Escape Analysis.
> Escape is a confirmed bug that was reported by someone who is not involved in PMDK development.
> As a PMDK team, we want to periodically take a time to look at those bugs,
> ```

the PMDK
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 18 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRBFOh8FCsVIwXN-Ko:-MdRBFOh8FCsVIwXN-Kp:blm4cis) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L18)):*
> ```
> should come with tests that prove that the change is correct and works.
> For bug fixes, this means that we have to write a test that reproduces a problem, then make a bug fix, so that test will pass.
> But anyway escape analysis allows us to double-check if we don't miss any occasion to improve the quality of the PMDK.
> ```

anyway,
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 23 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRBd6T4Kt1YkZ8H384:-MdRBd6T4Kt1YkZ8H385:b7v1gbg) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L23)):*
> ```
> ### How we do an Escape Analysis
> First of all, we have to find all bugs which were reported at this time and select those which meet the requirements of being categorized as an Escape.
> For a reminder, there are two things with must be true, to say that a bug is an Escape:
> ```

**which** must be true
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 25 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRBk791TD46BlJyRxg:-MdRBk791TD46BlJyRxh:b-o8gfjr) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L25)):*
> ```
> For a reminder, there are two things with must be true, to say that a bug is an Escape:
> * It must be a confirmed bug.
> * It must be found by someone who is not involved in PMDK development.
> ```

in **the** PMDK
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 27 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRC613A2nun-yMSmi9:-MdRC613A2nun-yMSmiA:b-kn61ja) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L27)):*
> ```
> * It must be found by someone who is not involved in PMDK development.
> 
> When we have such a list, we are going thru this list, and try to find what failed in our process that we didn't found this bug by ourselves.
> ```

thru -> through
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 37 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRD4yD2NwPwU7H1mEm:-MdRD4yD2NwPwU7H1mEn:bkt4dav) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L37)):*
> ```
> Since 01-01-2021 6 escapes were found. Five were found in PMDK repository, and one in libpmemobj-cpp.
> 
> Two first bugs on our list are:
> ```

First two
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 39 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRDORq0b1xAYe3ghm2:-MdRDORr6wdSWsCv-4Lg:b-bl7kn6) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L39)):*
> ```
> Two first bugs on our list are:
> [Make Check failed on Arm64][5255] and [pmempool_sync/TEST6 fails on ppc64le using device dax][5112]
> Both issues we labeled as "QA Escape: Excremental Feature". Arm and ppc ports are marked as experimental,
> ```

excremental -> experimental
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 45 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRDjUIDx8Sr1cfl2fz:-MdRDjUIDx8Sr1cfl2g-:b-z1p7je) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L45)):*
> ```
> The next one is embarrassing. [Multiple inconsistency bugs in libpmemobj array example program][5217] we marked as "QA Escape: known issue".
> We knew that this example is broken and for some reason, we forgot to remove it. Lesson learned: if something is broken in documentation, an example, or a comment,
> fix it, or delete it immediately. It's better to don't have documentation than to have misleading one.
> ```

not to have a documentation
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 52 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRFChh3yIqDlB9Ee3J:-MdRFChh3yIqDlB9Ee3K:b-quxcow) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L52)):*
> ```
> 
> The last escape in the PMDK repository was a [Missing recovery for hashmap atomic in mapcli][5220]. We created really limited tests for our examples
> they are mostly limited to compile and run it in the most basic scenario, just to ensure if its still "works". This issue and the array [one][5217] show
> ```

Begin a new sentence with **They**
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 52 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRFKm_1ng4P50hhc9R:-MdRFKm_1ng4P50hhc9S:b-q2dkh2) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L52)):*
> ```
> 
> The last escape in the PMDK repository was a [Missing recovery for hashmap atomic in mapcli][5220]. We created really limited tests for our examples
> they are mostly limited to compile and run it in the most basic scenario, just to ensure if its still "works". This issue and the array [one][5217] show
> ```

**it** still works
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 64 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRFid56vC-8_99SVDd:-MdRFid56vC-8_99SVDe:b-kyo26v) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L64)):*
> ```
> Escape Analysis allowed us to find minor improvements in our QA process, so it fulfilled our expectations.
> I would like to take a moment to say thank you to the entire PMDK team for their outstanding job in ensuring PMDK quality.
> Also, we want to say thank you to all of you who invested time in testing, analyze code, or even filing a bug report.
> ```

analyzing code
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 65 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRFnJaDyU9yxILeHjS:-MdRFnJaDyU9yxILeHjT:b-uzuwd) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L65)):*
> ```
> I would like to take a moment to say thank you to the entire PMDK team for their outstanding job in ensuring PMDK quality.
> Also, we want to say thank you to all of you who invested time in testing, analyze code, or even filing a bug report.
> This helps us to constantly improve PMDK, so others users will have a better experience with it.
> ```

other users

**Review by lplewa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/157)* status: 0 of 1 files reviewed, 21 unresolved discussions (waiting on @lplewa, @lukaszstolarczuk, and @PatKamin)

___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 2 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQdW3j0NiCESdIJoip:-Mdqrh0v2QsNCR8yYij6:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why uppercase E.A. ? I don't think it's a proper noun :wink:
(in the entire blog post)
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 3 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQbfi62aF6CA4mXQhN:-MdqrhLXEiYgySVocMoU:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

your gh login
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 18 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRBFOh8FCsVIwXN-Ko:-Mdqrm0Q4Vna-YdaxYW0:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L18)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

anyway,
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 21 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQcobZ7VXTA0wHXL1Y:-Mdqrmnz8s0_p4FSh-oM:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`How do we do`
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 23 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRBd6T4Kt1YkZ8H384:-Mdqrnhz7JmCsQvrjPZ-:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L23)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

**which** must be true
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 27 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRC613A2nun-yMSmi9:-Mdqrpgo7fcXGv6ELH75:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L27)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

thru -> through
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 37 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRD4yD2NwPwU7H1mEm:-MdqrqH-Bd60PaOpPz2n:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L37)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

First two
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQd0L9442ROTZ4q8uT:-MdqrrCfEuALlfnnACCF:b-7m0ag0) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

put all these names of the issues in quotes or maybe add a **bold**
</blockquote></details>

I used links so they should be visible
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 39 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRDORq0b1xAYe3ghm2:-Mdqrx1P5UsboCCbLzXM:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L39)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

excremental -> experimental
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 45 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRDjUIDx8Sr1cfl2fz:-MdqrxPIERkQXZ64-TGr:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L45)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

not to have a documentation
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 52 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRFKm_1ng4P50hhc9R:-MdqsK253kmfNilw8ktI:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L52)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

**it** still works
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 64 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRFid56vC-8_99SVDd:-MdqsKsE8DKO6YIixkcE:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L64)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

analyzing code
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 65 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdRFnJaDyU9yxILeHjS:-MdqsLCwDgLGaXPaiwHw:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L65)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

other users
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 71 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQcOyi0S9-RlyYyrX_:-MdqsLiX67rhPvilw2Ta:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L71)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls fix all the random empty lines
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/157)* status: all files reviewed, 10 unresolved discussions (waiting on @lplewa and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQdGEtDjBhD0IEC1xv:-Mdw9CNHE7mxta9_kv2G:b-u97zk9) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a link to the preview of generated post
</blockquote></details>

still missing 

---
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 2 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQdW3j0NiCESdIJoip:-Mdw9NrY0ifp1CJEeT09:b-t0gsl2) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L2)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still some occurrences of uppercase E.A. in the post
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 5 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQbwQh09QAav10U9tn:-Mdw9APC8EHA_hD0Sn8T:b-u93p5e) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. `analysis`
2. usually lowercase
</blockquote></details>

still misspell
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 21 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQcobZ7VXTA0wHXL1Y:-Mdw9Jh2Eed1fHEGYU75:bb7lgjf) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L21)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nope
___
*[_posts/2021/2021-07-01-Escape_Analysis_H1`2021, line 71 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/157#-MdQcOyi0S9-RlyYyrX_:-Mdw9WuHB9uTsNDOwvou:b-3pgfxs) ([raw file](https://github.com/pmem/pmem.github.io/blob/a270ee6977c4ad4a5cbc861e3236f80b17e1146c/_posts/2021/2021-07-01-Escape_Analysis_H1`2021#L71)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nope, still some empty lines at the end of the post

**Pull request closed without merging**
