### PR TITLE
Add information about the discontinuation of the vltrace and pynvm

### PR DESCRIPTION
**Pull request by szadam**
preview:
https://szadam.github.io/repoindex/
https://szadam.github.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/343)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/343)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @szadam and @wlemkows)

___
*[`content/blog/2022/update-pmdk-project-status.md` line 74 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/343#-NRCm6VT6kel_y69L9lw:-NRCm6VT6kel_y69L9lx:b2lkax) ([raw file](https://github.com/pmem/pmem.github.io/blob/113cce11c042f6b22bbdefe5d97f64a55a015e08/content/blog/2022/update-pmdk-project-status.md#L74)):*
> ```Markdown
> | Libvmem | https://github.com/pmem/vmem | No further support or maintenance planned |
> | Libpmemobj-cpp | https://github.com/pmem/libpmemobj-cpp | No further support or maintenance planned |
> | Libpmemkv<br/> and its language bindings | https://github.com/pmem/pmemkv | No further support or maintenance planned |
> ```

You can just put all the links to repos in the same row of the table. Please don't add a separate row (of the table) for each binding - you can use `<br />` (like e.g. libpmem, libpmem2 ...)

**Comment by szadam** [comment]
*[`content/blog/2022/update-pmdk-project-status.md` line 74 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/343#-NRCm6VT6kel_y69L9lw:-NRCpuo0C4eA31krtKHX:br7r3jb) ([raw file](https://github.com/pmem/pmem.github.io/blob/113cce11c042f6b22bbdefe5d97f64a55a015e08/content/blog/2022/update-pmdk-project-status.md#L74)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

You can just put all the links to repos in the same row of the table. Please don't add a separate row (of the table) for each binding - you can use `<br />` (like e.g. libpmem, libpmem2 ...)
</blockquote></details>

I think it is good like it is. If I add everything in one row (names of binding and links), it would cause some problems on the page depending on the size of the browser window.

**Review by szadam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/343)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`content/blog/2022/update-pmdk-project-status.md` line 78 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/343#-NR9H_BW5EWPLttLFbXB-r1-78:-NRCtDF4-JaCU8UEkn0z:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/113cce11c042f6b22bbdefe5d97f64a55a015e08/content/blog/2022/update-pmdk-project-status.md#L78)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

and pmemkv-bench
</blockquote></details>

Done.

**Review by wlemkows — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/343#-:-NRCuFaG1VhHvkXMR8Uo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[`content/blog/2022/update-pmdk-project-status.md` line 74 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/343#-NRCm6VT6kel_y69L9lw:-NRCuH5w2LbKGmEnxBVV:bb7k0qh) ([raw file](https://github.com/pmem/pmem.github.io/blob/113cce11c042f6b22bbdefe5d97f64a55a015e08/content/blog/2022/update-pmdk-project-status.md#L74)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

I think it is good like it is. If I add everything in one row (names of binding and links), it would cause some problems on the page depending on the size of the browser window.
</blockquote></details>

lgtm

**Review by wlemkows — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/343)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[`content/blog/2022/update-pmdk-project-status.md` line 74 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/343#-NRCm6VT6kel_y69L9lw:-NRCuliv57RL0R4Tzt8e:b-awzu11) ([raw file](https://github.com/pmem/pmem.github.io/blob/113cce11c042f6b22bbdefe5d97f64a55a015e08/content/blog/2022/update-pmdk-project-status.md#L74)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

I think it can stay in separate rows to avoid possible issues. It doesn't look so bad.

**Pull request merged**
