### PR TITLE
rpma: update pmem.io benchmarking manuals for ICX

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/227)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/227)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/227)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[content/rpma/documentation/basic-direct-write-to-pmem.md, line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/227#-N-23rc46pESXSedlzrt:-N-23rc46pESXSedlzru:b-od6fdm) ([raw file](https://github.com/pmem/pmem.github.io/blob/b053d78f14f1a94d103838b6bf87a166fe61bafd/content/rpma/documentation/basic-direct-write-to-pmem.md#L16)):*
> ```Markdown
> # Direct Write to PMem
> 
> *Direct Write to PMem* is a readiness of hardware and software configuration which allows effectively and persistently write data to PMem physically attached to one system from another system using RDMA-capable network. How to achieve *Direct Write to PMem* capability may differs from system to system because of variety of potential ‘interruptions’ (e.g. caching) in data’s way to be stored persistently on PMem.
> ```

`may differ` - please fix it by the way



_Code quote:_
```Markdown
may differs 
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/227)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[content/rpma/documentation/basic-direct-write-to-pmem.md, line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/227#-N-23rc46pESXSedlzrt:-N-271wq-z02dDJj45bl:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b053d78f14f1a94d103838b6bf87a166fe61bafd/content/rpma/documentation/basic-direct-write-to-pmem.md#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`may differ` - please fix it by the way
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/227#-:-N-28ytN09xpgpVgM6Tm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/227#-:-N-2z3xg5Ez-lUXpRMVB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/227)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
