### PR TITLE
Link fixes - additional patch

### PR DESCRIPTION
**Pull request by kswiecicki**
A small change answering issues raised in https://github.com/pmem/pmem.github.io/pull/238.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/239)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
great job, thanks!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/239#-:-N1sWqVqAx8ZTPW4hzHN:b-r3nr4x)* status: all files reviewed, 1 unresolved discussion (waiting on @kswiecicki)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/239#-N1sWrlL3zT_aCZEV_NV:-N1sWrlL3zT_aCZEV_NW:b-b6c2os) (no related file):*
did you manage to fix **all** broken links from https://github.com/pmem/pmem.github.io/issues/200 ?

___
___
*[`content/blog/2019/cpp-vector.md` line 142 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/239#-N1sWjySA-jT3NfQ6LHt:-N1sWjySA-jT3NfQ6LHu:bp2fxid) ([raw file](https://github.com/pmem/pmem.github.io/blob/65694f3399febe99ddd7a3dd273dd45e2c699534/content/blog/2019/cpp-vector.md#L142)):*
> ```Markdown
> #include <libpmemobj++/experimental/slice.hpp>
> 
> using vector_type = pmem::obj::experimental::vector<int>;
> ```

if you want to be precise, there are still few "experimentals" here

**Comment by kswiecicki** [comment]
*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/239#-N1sWrlL3zT_aCZEV_NV:-N1sY6VTCJmgMlJfC0m-:b54duyp) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

did you manage to fix **all** broken links from https://github.com/pmem/pmem.github.io/issues/200 ?
</blockquote></details>

No, there were some links to articles that are no longer available and I couldn't find a replacement for them.

**Comment by kswiecicki** [comment]
*[`content/blog/2019/cpp-vector.md` line 142 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/239#-N1sWjySA-jT3NfQ6LHt:-N1sYN0CA97ZIrrKN-C1:b8y303e) ([raw file](https://github.com/pmem/pmem.github.io/blob/65694f3399febe99ddd7a3dd273dd45e2c699534/content/blog/2019/cpp-vector.md#L142)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you want to be precise, there are still few "experimentals" here
</blockquote></details>

I didn't want to change anything other than the links and their labels.
There's a note at the start of the article that says that the `vector` is no longer experimental. For that reason, I avoided changing the code snippets.
I can do that if you want.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/239#-:-N1siov_6avqKwJVD-Bm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kswiecicki)

___
*[`content/blog/2019/cpp-vector.md` line 142 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/239#-N1sWjySA-jT3NfQ6LHt:-N1silJ02GqVDzW1Pgy1:b-ohkw6s) ([raw file](https://github.com/pmem/pmem.github.io/blob/65694f3399febe99ddd7a3dd273dd45e2c699534/content/blog/2019/cpp-vector.md#L142)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

I didn't want to change anything other than the links and their labels.
There's a note at the start of the article that says that the `vector` is no longer experimental. For that reason, I avoided changing the code snippets.
I can do that if you want.
</blockquote></details>

naah, I think it's all right

**Pull request merged**
