### PR TITLE
pmdk: set libpmemblk as deprecated

### PR DESCRIPTION
**Pull request by osalyk**
https://github.com/pmem/pmdk/pull/5538

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/338)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/338)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/338#-NQVND1zCwu1BH_5Br7s:-NQVRIV-BHPFsApryNfm:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update `/repoindex` as well with strikethrough for blk 
</blockquote></details>

Done.

___

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/338#-:-NQVUksb-RnhmuhibIBJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by szadam — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/338)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szadam — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/338#-:-NQ_kTKrC22mx2i0IKSr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
