### PR TITLE
Add blog post about concurrent associative data structures

### PR DESCRIPTION
**Pull request by vinser52**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/164)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/164)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @vinser52)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MjYbsAhAAs16cYKFJUB:-MjYbsAhAAs16cYKFJUC:b5qfg6i) (no related file):*
when you're done with the content, please push this into your gh-pages, so we have a nice readable preview of this blog post.

---
___
*[_posts/2021/2021-09-13-concurrent_associative_data_structures.md, line 3 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MjYUvx-0o9tDptKVSHZ:-MjYUvx-0o9tDptKVSH_:brmapay) ([raw file](https://github.com/pmem/pmem.github.io/blob/7498b574ad7c191ebaa9ddba93621788329b2edb/_posts/2021/2021-09-13-concurrent_associative_data_structures.md#L3)):*
> ```Markdown
> ---
> title: Concurrent associative data structures in libpmemobj-cpp
> author: svinogra
> ```

it should be your gh login - `vinser52`
___
*[_posts/2021/2021-09-13-concurrent_associative_data_structures.md, line 9 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MjYZUGCEd2mwweLBWDX:-MjYZUGCEd2mwweLBWDY:b-n4q2vv) ([raw file](https://github.com/pmem/pmem.github.io/blob/7498b574ad7c191ebaa9ddba93621788329b2edb/_posts/2021/2021-09-13-concurrent_associative_data_structures.md#L9)):*
> ```Markdown
> 
> ## Introduction
> This blog post describes design approaches of two concurrent data structures available in the libpmemobj-cpp library: ```pmem::obj::concurrent_hash_map``` and ```pmem::obj::concurrent_map```. Both are associative data structures composed of a collection of key and value pairs, such that each possible key appears at most once in the collection. The main difference between them is that the concurrent hash map is unordered, while the concurrent map is ordered by keys. The ```pmem::obj::concurrent_map``` and ```pmem::obj::concurrent_hash_map``` structures were inspired by the [oneAPI Threading Building Blocks (oneTBB)](https://github.com/oneapi-src/oneTBB) library which provides implementations of these concurrent data structures designed for volatile memory. The ```concurrent``` term means that data strcutres are intended for use in parallel environment when multiple threads can concurrently call methods of a data structure without additional synchronization required. These data structures designed to reside on persistentn memory and uses design consideration described in the [previous blog post](https://pmem.io/2021/07/28/concurrency.html).<br/>
> ```

`strcutres` misspell
___
*[_posts/2021/2021-09-13-concurrent_associative_data_structures.md, line 9 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MjYZfJk4IdsebLXhFLf:-MjYZfJk4IdsebLXhFLg:b-xbbx3s) ([raw file](https://github.com/pmem/pmem.github.io/blob/7498b574ad7c191ebaa9ddba93621788329b2edb/_posts/2021/2021-09-13-concurrent_associative_data_structures.md#L9)):*
> ```
> These data structures designed
> ```
are designed
___
*[_posts/2021/2021-09-13-concurrent_associative_data_structures.md, line 9 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MjYZm3E6EgiXP5nd2lX:-MjYZm3E6EgiXP5nd2lY:ba3u4f5) ([raw file](https://github.com/pmem/pmem.github.io/blob/7498b574ad7c191ebaa9ddba93621788329b2edb/_posts/2021/2021-09-13-concurrent_associative_data_structures.md#L9)):*
> ```Markdown
> 
> ## Introduction
> This blog post describes design approaches of two concurrent data structures available in the libpmemobj-cpp library: ```pmem::obj::concurrent_hash_map``` and ```pmem::obj::concurrent_map```. Both are associative data structures composed of a collection of key and value pairs, such that each possible key appears at most once in the collection. The main difference between them is that the concurrent hash map is unordered, while the concurrent map is ordered by keys. The ```pmem::obj::concurrent_map``` and ```pmem::obj::concurrent_hash_map``` structures were inspired by the [oneAPI Threading Building Blocks (oneTBB)](https://github.com/oneapi-src/oneTBB) library which provides implementations of these concurrent data structures designed for volatile memory. The ```concurrent``` term means that data strcutres are intended for use in parallel environment when multiple threads can concurrently call methods of a data structure without additional synchronization required. These data structures designed to reside on persistentn memory and uses design consideration described in the [previous blog post](https://pmem.io/2021/07/28/concurrency.html).<br/>
> ```

I believe `<br/>` is not required... (?)
___
*[_posts/2021/2021-09-13-concurrent_associative_data_structures.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MjYaen0A-VkdVfdGTC3:-MjYaen1BbYZ_VHN-BIz:b-rx9xmf) ([raw file](https://github.com/pmem/pmem.github.io/blob/7498b574ad7c191ebaa9ddba93621788329b2edb/_posts/2021/2021-09-13-concurrent_associative_data_structures.md#L33)):*
> ```
> and step 1 executed before we acquired any locks
> ```
not sure what you meant by this sentence.
___
*[_posts/2021/2021-09-13-concurrent_associative_data_structures.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MjYak412LmMM9xdLHLJ:-MjYak412LmMM9xdLHLK:baqx10v) ([raw file](https://github.com/pmem/pmem.github.io/blob/7498b574ad7c191ebaa9ddba93621788329b2edb/_posts/2021/2021-09-13-concurrent_associative_data_structures.md#L33)):*
> ```
> fault-taulerant
> ```
misspell
___
*[_posts/2021/2021-09-13-concurrent_associative_data_structures.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MjYauKxCsCPbNLC8LJU:-MjYauKyBv18lsIQNHit:b-o1zvs0) ([raw file](https://github.com/pmem/pmem.github.io/blob/7498b574ad7c191ebaa9ddba93621788329b2edb/_posts/2021/2021-09-13-concurrent_associative_data_structures.md#L33)):*
> ```
> <br/>
> ```
pls, replace it with an empty line between these paragraphs.
___
*[_posts/2021/2021-09-13-concurrent_associative_data_structures.md, line 41 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MjYbeFx2rcXaZW-DWSm:-MjYbeFx2rcXaZW-DWSn:b-yvocxs) ([raw file](https://github.com/pmem/pmem.github.io/blob/7498b574ad7c191ebaa9ddba93621788329b2edb/_posts/2021/2021-09-13-concurrent_associative_data_structures.md#L41)):*
> ```
> <br/>
> ```
.

**Review by pbalcer — COMMENTED** [review]
please split lines at 80, otherwise lgtm (at least the parts that exist)

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/164#-:-Mjnt9mUBCr4ZzlWw86N:b-ol8gdb)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @vinser52)

**Comment by lukaszstolarczuk** [comment]
@vinser52, ping 😃

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/164)* status: 1 of 4 files reviewed, 13 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, @pbalcer, and @vinser52)

___
*[_posts/2021/2021-09-13-concurrent_associative_data_structures.md, line 9 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MlL-tt0AM-tLGjjJHcu:-MlL-tt1B8yMFRFDw2wv:bx97amj) ([raw file](https://github.com/pmem/pmem.github.io/blob/7498b574ad7c191ebaa9ddba93621788329b2edb/_posts/2021/2021-09-13-concurrent_associative_data_structures.md#L9)):*
> ```
> persistentn
> ```
persistentn -> persistent
___
*[_posts/2021/2021-09-13-concurrent_associative_data_structures.md, line 10 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MlL12PL1-IwewcBl3J-:-MlL12PL1-IwewcBl3J0:b-g5ajhn) ([raw file](https://github.com/pmem/pmem.github.io/blob/7498b574ad7c191ebaa9ddba93621788329b2edb/_posts/2021/2021-09-13-concurrent_associative_data_structures.md#L10)):*
> ```
> ```find```
> ```
generally in markdown format should also work for non-block (inline):

> ```
> `find`
> ```
which is a little bit easier to read
___
*[_posts/2021/2021-09-13-concurrent_associative_data_structures.md, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MlL2NG_BH9YD53gY--d:-MlL2NG_BH9YD53gY--e:b3qybmz) ([raw file](https://github.com/pmem/pmem.github.io/blob/7498b574ad7c191ebaa9ddba93621788329b2edb/_posts/2021/2021-09-13-concurrent_associative_data_structures.md#L13)):*
> ```
> The  ```pmem::obj::concurrent_map``` implementation is based on a concurrent skip list data structure. The [oneTBB](https://github.com/oneapi-src/oneTBB) library supplies ```tbb::concurrent_map```, which is designed for volatile memory.
> ```
We'd better to say that something like this: "We have some existing implementations of concurrent_map like this and this". Then explanation starts.
___
*[_posts/2021/2021-09-13-concurrent_associative_data_structures.md, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/164#-MlL2xUI2BU_AUUO1P1Z:-MlL2xUI2BU_AUUO1P1_:b-v6vvqi) ([raw file](https://github.com/pmem/pmem.github.io/blob/7498b574ad7c191ebaa9ddba93621788329b2edb/_posts/2021/2021-09-13-concurrent_associative_data_structures.md#L13)):*
> ```
> . But
> ```
should be:
> ```
> , but
> ```
This second sentence is a continuation

**Comment by lukaszstolarczuk** [comment]
Hey @vinser52, perhaps we could offer some kind of help to push this blog post into its final version?

**Comment by pbalcer** [comment]
I'm going to close this for now. Please create a new PR for the new website (once it's up).

**Pull request closed without merging**
