### PR TITLE
rpma: reports: CLX + MLX + CentOS 8.4 + FSDAX

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/222)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/222#-:-MyBlNGl3VPPRpT9s3CJ:bg7igkv)* status: 0 of 2 files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/222)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk and @osalyk)

___
*[content/rpma/reports/_index.md, line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/222#-MyBmThb-z-q-OZv1U2M:-MyBmThc2lfeuFjw_SoN:b-of0262) ([raw file](https://github.com/pmem/pmem.github.io/blob/eeb50002b2ebd896fa51d9e0b8c01ced98f8f71a/content/rpma/reports/_index.md#L16)):*
> ```Markdown
> 
> * [Intel® Cascade Lake + Mellanox® ConnectX®-5 + CentOS Linux 8.2 kernel 4.18 + Device DAX](/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.2.pdf)
> * [Intel® Cascade Lake + Mellanox® ConnectX®-5 + CentOS Linux 8.4 kernel 4.18 + File System DAX](/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf)
> ```

missing "enter" at the end of the file
___
*[static/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf, line 0 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/222#-MyBmWL75ySVa1EWHvGc:-MyBmWL75ySVa1EWHvGd:baqpf9y) ([raw file](https://github.com/pmem/pmem.github.io/blob/eeb50002b2ebd896fa51d9e0b8c01ced98f8f71a/static/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf#L0)):*
tbh, a git repository, in general, is not the "perfect" place for holding big/binary files... please consider uploading these reports onto some external storages

hint: in pmemkv we put a report along the release (as a GitHub's release artifact)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/222)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk and @osalyk)

___
*[content/rpma/reports/_index.md, line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/222#-MyBmThb-z-q-OZv1U2M:-MyBsy2s6NarC1x-HSmW:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/eeb50002b2ebd896fa51d9e0b8c01ced98f8f71a/content/rpma/reports/_index.md#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

missing "enter" at the end of the file
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/222)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[content/rpma/reports/_index.md, line 15 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/222#-MyCW_ee4kOXkr9a3R51:-MyCW_ee4kOXkr9a3R52:b-ymeo2r) ([raw file](https://github.com/pmem/pmem.github.io/blob/18710ef494dea6314e799b5108bb85c2c3600125/content/rpma/reports/_index.md#L15)):*
> ```Markdown
> ---
> 
> * [Intel® Cascade Lake + Mellanox® ConnectX®-5 + CentOS Linux 8.2 kernel 4.18 + Device DAX](/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.2.pdf)
> ```

https://github.com/pmem/rpma/releases/download/0.10.0/RPMA_Perf_report_CLX_MLX_CentOS8.2_DEVDAX.pdf



_Code quote:_
```Markdown
/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.2.pdf
```
___
*[content/rpma/reports/_index.md, line 16 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/222#-MyCWh3M7tytph-KFAsn:-MyCWh3M7tytph-KFAso:bmh89kx) ([raw file](https://github.com/pmem/pmem.github.io/blob/18710ef494dea6314e799b5108bb85c2c3600125/content/rpma/reports/_index.md#L16)):*
> ```Markdown
> 
> * [Intel® Cascade Lake + Mellanox® ConnectX®-5 + CentOS Linux 8.2 kernel 4.18 + Device DAX](/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.2.pdf)
> * [Intel® Cascade Lake + Mellanox® ConnectX®-5 + CentOS Linux 8.4 kernel 4.18 + File System DAX](/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf)
> ```

https://github.com/pmem/rpma/releases/download/0.10.0/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf



_Code quote:_
```Markdown
/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf
```
___
*[static/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf, line  at r1](https://reviewable.io/reviews/pmem/pmem.github.io/222#-MyBmWL75ySVa1EWHvGc:-MyCWjG9-VTY2oTpcMvC:b-6vwkqv) ([raw file](https://github.com/pmem/pmem.github.io/blob/eeb50002b2ebd896fa51d9e0b8c01ced98f8f71a/static/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf#L)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

tbh, a git repository, in general, is not the "perfect" place for holding big/binary files... please consider uploading these reports onto some external storages

hint: in pmemkv we put a report along the release (as a GitHub's release artifact)
</blockquote></details>

Good idea, thanks @lukaszstolarczuk ! :-)

@osalyk  please remove the directory `static/rpma/reports` at all.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/222)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ldorau and @lukaszstolarczuk)

___
*[content/rpma/reports/_index.md, line 15 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/222#-MyCW_ee4kOXkr9a3R51:-MyD3p_dCWj79pJTIgj3:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/18710ef494dea6314e799b5108bb85c2c3600125/content/rpma/reports/_index.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

https://github.com/pmem/rpma/releases/download/0.10.0/RPMA_Perf_report_CLX_MLX_CentOS8.2_DEVDAX.pdf
</blockquote></details>

Done.
___
*[content/rpma/reports/_index.md, line 16 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/222#-MyCWh3M7tytph-KFAsn:-MyD3uIn0PaHbfV7Bbnw:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/18710ef494dea6314e799b5108bb85c2c3600125/content/rpma/reports/_index.md#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

https://github.com/pmem/rpma/releases/download/0.10.0/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf
</blockquote></details>

Done.
___
*[static/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf, line  at r1](https://reviewable.io/reviews/pmem/pmem.github.io/222#-MyBmWL75ySVa1EWHvGc:-MyD4U7w5p34Hgb8jvgM:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/eeb50002b2ebd896fa51d9e0b8c01ced98f8f71a/static/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf#L)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Good idea, thanks @lukaszstolarczuk ! :-)

@osalyk  please remove the directory `static/rpma/reports` at all.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/222#-:-MyDK6IR4kdQecUjHKJ2:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

**Pull request merged**
