### PR TITLE
remove mention of librpmem and libpmemset from the blog

### PR DESCRIPTION
**Pull request by osalyk**
https://github.com/pmem/pmdk/pull/5495
  https://github.com/pmem/pmdk/pull/5513

This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/326)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/326)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/326#-NLa0vsB7vj2rAMpgbN4):*
pls mention links to PR in PMDK removing rpmem and set:

https://github.com/pmem/pmdk/pull/5495
https://github.com/pmem/pmdk/pull/5513
___
*[`content/blog/2022/update-pmdk-project-status.md` line 70 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/326#-NLa0ohHBDWYBy2-mKPb:-NLa0ohHBDWYBy2-mKPc:bkx1cg) ([raw file](https://github.com/pmem/pmem.github.io/blob/4a0ed0407eaceb073a56fa4406bfc9c984373e87/content/blog/2022/update-pmdk-project-status.md#L70)):*
> ```Markdown
> | librpma | https://github.com/pmem/rpma | Issue Reporting and Bug Fixes via GitHub and pmdk_support@intel.com<br /> Seeking new co-maintainer(s) to continue development towards production release |
> | Libpmemstream | https://github.com/pmem/pmemstream | Issue Reporting and Bug Fixes via GitHub and pmdk_support@intel.com<br /> Seeking new co-maintainer(s) to continue development towards production release |
> | Libpmemblk<br /> Libpmemlog<br /> Libpmemset | https://github.com/pmem/pmdk | No further support or maintenance planned |
> ```

set is also removed now

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/326)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/326#-NLa0vsB7vj2rAMpgbN4):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls mention links to PR in PMDK removing rpmem and set:

https://github.com/pmem/pmdk/pull/5495
https://github.com/pmem/pmdk/pull/5513
</blockquote></details>

Done.



_Code quote:_
```
  https://github.com/pmem/pmdk/pull/5495
  https://github.com/pmem/pmdk/pull/5513
```
___
*[`content/blog/2022/update-pmdk-project-status.md` line 70 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/326#-NLa0ohHBDWYBy2-mKPb:-NLaEdfK7KwkzVe7j-Pb:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/4a0ed0407eaceb073a56fa4406bfc9c984373e87/content/blog/2022/update-pmdk-project-status.md#L70)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

set is also removed now
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/326)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk and @wlemkows)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/326#-NLa0vsB7vj2rAMpgbN4):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

heh, so now you can update the first line of the commit msg :wink: 
___
*[`content/blog/2022/update-pmdk-project-status.md` line 70 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/326#-NLa0ohHBDWYBy2-mKPb:-NLaFUiz6uzmg45zTjTp:bb7p5eq) ([raw file](https://github.com/pmem/pmem.github.io/blob/4a0ed0407eaceb073a56fa4406bfc9c984373e87/content/blog/2022/update-pmdk-project-status.md#L70)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx!

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/326)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/326#-NLa0vsB7vj2rAMpgbN4):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, so now you can update the first line of the commit msg :wink: 
</blockquote></details>

Right, thx.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/326#-:-NLaaqx24UckzCZJiwjJ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wlemkows)

**Pull request merged**
