### PR TITLE
Add Bug and RFE issue templates

### PR DESCRIPTION
**Pull request by sscargal**
Add a Bug and 'Request for Enhancement/Feature Request' templates to GitHub to support the new pmem.io refresh.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/165)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/165)* status: all files reviewed, 4 unresolved discussions (waiting on @sscargal)

___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 11 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/165#-MkkeaSN84xBRUH7Gp3r:-MkkeaSN84xBRUH7Gp3s:b3qy3qx) ([raw file](https://github.com/pmem/pmem.github.io/blob/1a274214894c6176677217586e10b2950a7aac9c/.github/ISSUE_TEMPLATE/bug_report.md#L11)):*
> ```Markdown
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> ```

consider adding "how often bug is revealed" - perhaps it doesn't happen always
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 32 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/165#-Mkkf49V17WWcwTHn05O:-Mkkf49V17WWcwTHn05P:bsc02mp) ([raw file](https://github.com/pmem/pmem.github.io/blob/1a274214894c6176677217586e10b2950a7aac9c/.github/ISSUE_TEMPLATE/bug_report.md#L32)):*
> ```Markdown
>  - Device: [e.g. Desktop, Tablet, Mobile]
>  - OS: [e.g. MacOS X 12 , Windows 10, Ubuntu Linux 20.04]
>  - Browser [e.g. chrome, safari, firefox]
> ```

add `:` -> `Browser: ...`
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/165#-Mkkf8NEC93vaSkwUOLl:-Mkkf8NEC93vaSkwUOLm:b2kvmjr) ([raw file](https://github.com/pmem/pmem.github.io/blob/1a274214894c6176677217586e10b2950a7aac9c/.github/ISSUE_TEMPLATE/bug_report.md#L33)):*
> ```Markdown
>  - OS: [e.g. MacOS X 12 , Windows 10, Ubuntu Linux 20.04]
>  - Browser [e.g. chrome, safari, firefox]
>  - Browser Version [e.g. 22]
> ```

missing `:`
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 34 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/165#-MkkeH-sBI7MIwNieZMc:-MkkeH-t-tCTpQnyxI5z:bbetetb) ([raw file](https://github.com/pmem/pmem.github.io/blob/1a274214894c6176677217586e10b2950a7aac9c/.github/ISSUE_TEMPLATE/bug_report.md#L34)):*
> ```Markdown
>  - Browser [e.g. chrome, safari, firefox]
>  - Browser Version [e.g. 22]
> ```

consider adding "requested priority" - how annoying the bug is :wink:

**Comment by lukaszstolarczuk** [comment]
@sscargal, ping 😉 

I guess it should go to the `main` branch now.

**Review by sscargal — COMMENTED** [review]
Agreed. Changed the PR to merge into 'main' vs 'master'.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/165#-:-Mqz4E8T9zH6GqjHoFt9:b-dojxdt)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 11 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/165#-MkkeaSN84xBRUH7Gp3r:-Mqz46sP5O7qHjTvECUw:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/1a274214894c6176677217586e10b2950a7aac9c/.github/ISSUE_TEMPLATE/bug_report.md#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

consider adding "how often bug is revealed" - perhaps it doesn't happen always
</blockquote></details>

Done.
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 32 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/165#-Mkkf49V17WWcwTHn05O:-Mqz47T2Cd3EUzR1R35b:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/1a274214894c6176677217586e10b2950a7aac9c/.github/ISSUE_TEMPLATE/bug_report.md#L32)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add `:` -> `Browser: ...`
</blockquote></details>

Done.
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/165#-Mkkf8NEC93vaSkwUOLl:-Mqz47pU-jZQxTwAKKq9:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/1a274214894c6176677217586e10b2950a7aac9c/.github/ISSUE_TEMPLATE/bug_report.md#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

missing `:`
</blockquote></details>

Done.
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 34 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/165#-MkkeH-sBI7MIwNieZMc:-Mqz48LgDuGO2zSBhiXq:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/1a274214894c6176677217586e10b2950a7aac9c/.github/ISSUE_TEMPLATE/bug_report.md#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

consider adding "requested priority" - how annoying the bug is :wink:
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
thanks

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/165#-:-Mr19A_F7B9pmYjmk4S-:b-k73z76)* status: all files reviewed, 1 unresolved discussion (waiting on @sscargal)

___
*[-- commits, line 9 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/165#-Mr195yHAOZ6j3V-heGz):*
I guess you can squash your changes into one
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 12 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/165#-Mr18xht6zHRXAf0I6hv:-Mr18xht6zHRXAf0I6hw:b8co4q7) ([raw file](https://github.com/pmem/pmem.github.io/blob/7f064fe0061469782eb778abbfef18ce14971f35/.github/ISSUE_TEMPLATE/bug_report.md#L12)):*
> ```Markdown
> A clear and concise description of what the bug is.
> 
> **How often is the bug experiences?**
> ```

misspell(?) - `experienced`

**Review by sscargal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/165)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 12 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/165#-Mr18xht6zHRXAf0I6hv:-Mr36NDx7f2txeRE43C5:b-qbjso8) ([raw file](https://github.com/pmem/pmem.github.io/blob/7f064fe0061469782eb778abbfef18ce14971f35/.github/ISSUE_TEMPLATE/bug_report.md#L12)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

misspell(?) - `experienced`
</blockquote></details>

Yes. Good catch. Fixed.

**Pull request merged**
