### PR TITLE
add cxl software blog post

### PR DESCRIPTION
**Pull request by pbalcer**
Preview: https://pbalcer.github.io/blog/2023/05/exploring-the-software-ecosystem-for-compute-express-link-cxl-memory/

This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/356)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/356)* status: all files reviewed, 4 unresolved discussions (waiting on @pbalcer)

___
*[`content/blog/2023/cxl-blog-post.md` line 87 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NWhBslLChZ4cHnXMElv:-NWhBslLChZ4cHnXMElw:bx9peq6) ([raw file](https://github.com/pmem/pmem.github.io/blob/0dd7d3fae7896480bdb5ff307309b936738f958c/content/blog/2023/cxl-blog-post.md#L87)):*
> ```Markdown
> But, again, there is a difference in how regions are configured. With CXL, regions
> can now be dynamically configured at runtime using a utility called `cxl`, rather
> than being statically configured at boot through BIOS or ipmctl as in the case
> ```

perhaps make it: \`ipmctl\` to mark it as a command (similarly to \`cxl\`)
___
*[`content/blog/2023/cxl-blog-post.md` line 88 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NWhCGef6PEp2WhrGi7A:-NWhCGef6PEp2WhrGi7B:bpfa965) ([raw file](https://github.com/pmem/pmem.github.io/blob/0dd7d3fae7896480bdb5ff307309b936738f958c/content/blog/2023/cxl-blog-post.md#L88)):*
> ```Markdown
> can now be dynamically configured at runtime using a utility called `cxl`, rather
> than being statically configured at boot through BIOS or ipmctl as in the case
> of Intel Optane Persistent Memory.
> ```

"Intel(R) Optane(TM)" (?)
___
*[`content/blog/2023/cxl-blog-post.md` line 113 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NWhDlCQ2L_CiYEtPejw:-NWhDlCRAkonNZP7qz8d:b-nyzhdj) ([raw file](https://github.com/pmem/pmem.github.io/blob/0dd7d3fae7896480bdb5ff307309b936738f958c/content/blog/2023/cxl-blog-post.md#L113)):*
> ```Markdown
> a devdax namespace likewise configured into system-ram mode, also known as
> Kernel Memory DAX. This configuration means that we expect our CXL memory
> to be show up as an additional memory-only NUMA node in the system.
> ```

drop `be`
___
*[`content/blog/2023/cxl-blog-post.md` line 117 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NWhD0VUEIncpo4WrD2D:-NWhD0VUEIncpo4WrD2E:bi5c7jd) ([raw file](https://github.com/pmem/pmem.github.io/blob/0dd7d3fae7896480bdb5ff307309b936738f958c/content/blog/2023/cxl-blog-post.md#L117)):*
> ```Markdown
> ```C
> #include <memkind.h>
> …
> ```

This ellipsis is colored weirdly, perhaps remove or make it a comment
___
*[`content/blog/2023/cxl-blog-post.md` line 137 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NWhEAEV2tTtyvCY4Igk:-NWhEAEV2tTtyvCY4Igl:b-hgoegu) ([raw file](https://github.com/pmem/pmem.github.io/blob/0dd7d3fae7896480bdb5ff307309b936738f958c/content/blog/2023/cxl-blog-post.md#L137)):*
> ```Markdown
> for PMem, we can take advantage of the existing support for this feature in libmemkind.
> Creating a new allocation is straightforward. We simply need to call
> the memkind_malloc function with the appropriate option. The library will automatically
> ```

mark this as a command, using  \`

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/356)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`content/blog/2023/cxl-blog-post.md` line 87 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NWhBslLChZ4cHnXMElv:-NWvZlg20jmTkeujw7US:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0dd7d3fae7896480bdb5ff307309b936738f958c/content/blog/2023/cxl-blog-post.md#L87)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps make it: \`ipmctl\` to mark it as a command (similarly to \`cxl\`)
</blockquote></details>

Done.
___
*[`content/blog/2023/cxl-blog-post.md` line 113 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NWhDlCQ2L_CiYEtPejw:-NWvZmvM0A0fsFmB1dKA:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0dd7d3fae7896480bdb5ff307309b936738f958c/content/blog/2023/cxl-blog-post.md#L113)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

drop `be`
</blockquote></details>

Done.
___
*[`content/blog/2023/cxl-blog-post.md` line 137 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NWhEAEV2tTtyvCY4Igk:-NWvZnNl6N1TePh8b2-b:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0dd7d3fae7896480bdb5ff307309b936738f958c/content/blog/2023/cxl-blog-post.md#L137)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

mark this as a command, using  \`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/356)* status: all files reviewed, 3 unresolved discussions (waiting on @pbalcer)

___
*[`content/blog/2023/cxl-blog-post.md` line 75 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NYNdbkr5izBEsrZATm2:-NYNdbkr5izBEsrZATm3:b-mycjiy) ([raw file](https://github.com/pmem/pmem.github.io/blob/072ff57e26c1cf8b63db67bb96e20708db53f320/content/blog/2023/cxl-blog-post.md#L75)):*
> ```Markdown
> are statically defined by ACPI, CXL memory regions are dynamic. As a result,
> an additional configuration step might now be necessary to create these regions when needed.
> For volatile memory, this is handled performed automatically.
> ```

drop `performed` (?)
___
*[`content/blog/2023/cxl-blog-post.md` line 176 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NYNbPuB1RgLMvdbqoUJ:-NYNbPuB1RgLMvdbqoUK:b2kv30d) ([raw file](https://github.com/pmem/pmem.github.io/blob/072ff57e26c1cf8b63db67bb96e20708db53f320/content/blog/2023/cxl-blog-post.md#L176)):*
> ```Markdown
> [fixed-kind-example]: https://github.com/memkind/memkind/blob/master/examples/fixed_malloc.c
> [steves-qemu-cxl-post]: https://stevescargall.com/blog/2022/01/20/how-to-emulate-cxl-devices-using-kvm-and-qemu/
> [run_qemu_gh]: https://github.com/pmem/run_qemu
> ```

missing EOF
___
*[`layouts/shortcodes/table.html` line 1 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NYNbUkP5qKZuuW5YpYM:-NYNbUkP5qKZuuW5YpYN:b-oerzko) ([raw file](https://github.com/pmem/pmem.github.io/blob/072ff57e26c1cf8b63db67bb96e20708db53f320/layouts/shortcodes/table.html#L1)):*
> ```HTML
> {{ $htmlTable := .Inner | markdownify }}
> ```

are you sure we need this shortcode? is there anything special here I'm not seeing?

we should already have a table defined - used e.g. in https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/356)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`content/blog/2023/cxl-blog-post.md` line 75 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NYNdbkr5izBEsrZATm2:-NYNfGcQ3ylruPXRe_r-:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/072ff57e26c1cf8b63db67bb96e20708db53f320/content/blog/2023/cxl-blog-post.md#L75)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

drop `performed` (?)
</blockquote></details>

Done.
___
*[`content/blog/2023/cxl-blog-post.md` line 176 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NYNbPuB1RgLMvdbqoUJ:-NYNfGwCDcf_L_V8KnPh:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/072ff57e26c1cf8b63db67bb96e20708db53f320/content/blog/2023/cxl-blog-post.md#L176)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

missing EOF
</blockquote></details>

Done.
___
*[`layouts/shortcodes/table.html` line 1 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NYNbUkP5qKZuuW5YpYM:-NYNgnnhAOWV1VL2p9ZB:b-m8ki03) ([raw file](https://github.com/pmem/pmem.github.io/blob/072ff57e26c1cf8b63db67bb96e20708db53f320/layouts/shortcodes/table.html#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are you sure we need this shortcode? is there anything special here I'm not seeing?

we should already have a table defined - used e.g. in https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/
</blockquote></details>

I haven't updated my fork in a long time :D
Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/356#-:-NYNyoA01I3Lx3n57FtI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pbalcer)

___
*[`layouts/shortcodes/table.html` line 1 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/356#-NYNbUkP5qKZuuW5YpYM:-NYNyl-YAGuLSA1RjwGc:b-ve3yvb) ([raw file](https://github.com/pmem/pmem.github.io/blob/072ff57e26c1cf8b63db67bb96e20708db53f320/layouts/shortcodes/table.html#L1)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I haven't updated my fork in a long time :D
Done.
</blockquote></details>

:smile:

**Review by igchor — APPROVED** [review]

**Comment by igchor** [comment]
Perhaps you could also mention that if an app used fsdax in volatile mode, it can now use tmpfs on top of specific NUMA node to avoid code changes (like we did in CacheLib).

**Comment by pbalcer** [comment]
I added "Volatile use of fsdax" and mentioned the tmpfs approach.

**Pull request merged**
