### PR TITLE
Pmdk summary

### PR DESCRIPTION
**Pull request by grom72**
Requires:
- [x] #368

Preview:
https://grom72.github.io/pmdk/

This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/367)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/367)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72)

___
*[`data/en/pmdk.yml` line 15 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaWqSy1XkdYcCuywZL:-NcaWqSy1XkdYcCuywZM:b45h) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L15)):*
> ```YAML
>   title: ''
>   content_banner:
>     bold_text: '<p>The <a href=\"https://github.com/pmem/pmdk/\">PMDK repository on the GitHub</a> has been the ultimate source of information since the release 2.0.0!</p>'
> ```





_Suggestion:_
```YAML
'<p>The <a href=\"https://github.com/pmem/pmdk/\">PMDK repository</a> on GitHub is the ultimate source of information from release 2.0!</p>'
```
___
*[`data/en/pmdk.yml` line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaXK-B2MyiK-aE5oYK:-NcaXK-B2MyiK-aE5oYL:b45h) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L16)):*
> ```YAML
>   content_banner:
>     bold_text: '<p>The <a href=\"https://github.com/pmem/pmdk/\">PMDK repository on the GitHub</a> has been the ultimate source of information since the release 2.0.0!</p>'
>     text: 'This website is valid up to PMDK release 1.13.0. It is not guaranteed that the content of this site reflects the latest state of PMDK-related knowledge.'
> ```





_Suggestion:_
```YAML
'The PMDK documentation collected here should be valid up to the 1.13.1 release but is maintained only on a best-effort basis and may not reflect the latest state of the art.'
```
___
*[`data/en/pmdk.yml` line 21 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaYQiE3PlP6PU3uw-x:-NcaYQiE3PlP6PU3uw-y:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L21)):*
> ```YAML
> libraries_section:
>   enable: true
>   title: "<p>The following libraries are part of the PMDK starting release 2.0.0.</p>"
> ```





_Suggestion:_
```YAML
The following libraries are active parts of the PMDK.
```
___
*[`data/en/pmdk.yml` line 29 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaYz248jtkPtnfQ7ul:-NcaYz248jtkPtnfQ7um:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L29)):*
> ```YAML
>     library_item2:
>       title: 'libpmem'
>       content: "<p>The <strong>libpmem</strong> library provides low level persistent memory support. The libraries above are implemented using <strong>libpmem</strong>. Developers wishing to roll their own persistent memory algorithms will find this library useful, but most developers will likely use <strong>libpmemobj</strong> above and let that library call <strong>libpmem</strong> for them.</p>
> ```





_Suggestion:_
```YAML
The <strong>libpmem</strong> library provides low-level persistent memory support.
```
___
*[`data/en/pmdk.yml` line 33 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaZ_qJEvpJpbpoi4ok:-NcaZ_qJEvpJpbpoi4ol:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L33)):*
> ```YAML
>     library_item3:
>       title: 'libpmem2'
>       content: "<p>The <strong>libpmem2</strong> library provides low level persistent memory support. The library is a new version of <strong>libpmem</strong>. <strong>libpmem2</strong> provides a more universal and platform-agnostic interface. Developers wishing to roll their own persistent memory algorithms will find this library useful, but most developers will likely use <strong>libpmemobj</strong> above that provides memory allocation and transactions support.</p>
> ```





_Suggestion:_
```YAML
<p>The <strong>libpmem2</strong> library provides low-level persistent memory support.
```
___
*[`data/en/pmdk.yml` line 35 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaZWpo-tibN-OTWhEr:-NcaZWpo-tibN-OTWhEs:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L35)):*
> ```YAML
>       content: "<p>The <strong>libpmem2</strong> library provides low level persistent memory support. The library is a new version of <strong>libpmem</strong>. <strong>libpmem2</strong> provides a more universal and platform-agnostic interface. Developers wishing to roll their own persistent memory algorithms will find this library useful, but most developers will likely use <strong>libpmemobj</strong> above that provides memory allocation and transactions support.</p>
>                 <p>See the <a href=\"./libpmem2\">libpmem2 page</a> for documentation and examples.</p>
>                 <blockquote><p><strong>Note:</strong>Support for experimental <strong>async</strong> functions is available only in the release 1.13.0 and before.</p></blockquote>"
> ```





_Suggestion:_
```YAML
<strong>Note: </strong>Support
```
___
*[`data/en/pmdk.yml` line 56 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-Ncb-BQG5PMWf1Hvl5Xx:-Ncb-BQICQwSIOBeTl8y:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L56)):*
> ```YAML
> Discontinuation:
>   enable: true
>   title: 'Discontinuation of the project'
> ```





_Suggestion:_
```YAML
Discontinued projects
```
___
*[`data/en/pmdk.yml` line 59 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-Ncb-ZuHAH3z5aF3UXQM:-Ncb-ZuHAH3z5aF3UXQN:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L59)):*
> ```YAML
>   lists:
>     branch_list1: 
>       content: "<p>The <strong>libpmemblk</strong>, <strong>libpmemlog</strong>, <strong>librpma</strong>, <strong>libpmemset</strong>, <strong>libvmem</strong>, <strong>librpmem</strong>, <strong>libvmemcache</strong>, <strong>pmdk-convert</strong>, <strong>libpmemobj-cpp</strong> and <strong>pmemkv</strong> libraries will no longer be maintained by Intel.</p>"
> ```





_Suggestion:_
```YAML
content: "<p>The following libraries are no longer maintained. If you need to use any of these projects, are interested in independently developing it, or would like to maintain patches for the open-source software community, please create your own fork for the project of interest. You will find more information <a href=\"/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/\">here</a>.</p>"
```
___
*[`data/en/pmdk.yml` line 70 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-Ncb-Xj_-iXOYMfewpWe:-Ncb-Xj_-iXOYMfewpWf:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L70)):*
> ```YAML
>                     maintain patches for the open source software community, please create your own fork of this project."
>         list_item4:
>           content: "You will find more information <a href=\"/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/\">here</a>."
> ```


___
*[`data/en/pmdk.yml` line 73 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-Ncb-n9_8j0U1Wvv7dFA:-Ncb-n9_8j0U1Wvv7dFB:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L73)):*
> ```YAML
> 
>     branch_list2:
>       content: "<p>Support for <strong>Windows</strong> and <strong>FreeBSD</strong> are deprecated since <strong>PMDK 1.13.0</strong> release and will be removed in the <strong>PMDK 2.0.0</strong> release.</p>"
> ```





_Suggestion:_
```YAML
Support for <strong>Windows</strong> and <strong>FreeBSD</strong> has been deprecated since the <strong>PMDK 1.13.0</strong> release and was removed in the <strong>PMDK 2.0.0 release</strong>.
```
___
*[`data/en/pmdk.yml` line 79 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-Ncb0SRVE0f6dpp-QTDg:-Ncb0SRVE0f6dpp-QTDh:bhw1vg9) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L79)):*
> ```YAML
>   enable: true
>   title: 'Documentation of discontinuated componennts'
>   content: "<p>The <strong>libpmemblk</strong> library supports arrays of pmem-resident blocks, all the same size, that are atomically updated. For example, a program keeping a cache of fixed-size objects in pmem might find this library useful.</p>"
> ```

I believe this part is not used at all, is it?
___
*[`themes/pmem-hugo/layouts/pmdk/list.html` line 25 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaUUWEA_LtIvXMW1XX:-NcaUUWFBwXlG6DDuVpQ:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/themes/pmem-hugo/layouts/pmdk/list.html#L25)):*
> ```HTML
> 
> ```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/367)* status: 0 of 33 files reviewed, 12 unresolved discussions (waiting on @janekmi)

___
*[`data/en/pmdk.yml` line 15 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaWqSy1XkdYcCuywZL:-Ncc03cW9DE72Bm7rkAZ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L15)):*
> ```YAML
>   title: ''
>   content_banner:
>     bold_text: '<p>The <a href=\"https://github.com/pmem/pmdk/\">PMDK repository on the GitHub</a> has been the ultimate source of information since the release 2.0.0!</p>'
> ```

Done.
___
*[`data/en/pmdk.yml` line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaXK-B2MyiK-aE5oYK:-Ncc08x78RhEyzYAEmDB:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L16)):*
> ```YAML
>   content_banner:
>     bold_text: '<p>The <a href=\"https://github.com/pmem/pmdk/\">PMDK repository on the GitHub</a> has been the ultimate source of information since the release 2.0.0!</p>'
>     text: 'This website is valid up to PMDK release 1.13.0. It is not guaranteed that the content of this site reflects the latest state of PMDK-related knowledge.'
> ```

Done.
___
*[`data/en/pmdk.yml` line 21 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaYQiE3PlP6PU3uw-x:-Ncc0Gy77ifJqUDgSbdu:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L21)):*
> ```YAML
> libraries_section:
>   enable: true
>   title: "<p>The following libraries are part of the PMDK starting release 2.0.0.</p>"
> ```

Done.
___
*[`data/en/pmdk.yml` line 29 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaYz248jtkPtnfQ7ul:-Ncc0IRn0N3MulbnnExv:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L29)):*
> ```YAML
>     library_item2:
>       title: 'libpmem'
>       content: "<p>The <strong>libpmem</strong> library provides low level persistent memory support. The libraries above are implemented using <strong>libpmem</strong>. Developers wishing to roll their own persistent memory algorithms will find this library useful, but most developers will likely use <strong>libpmemobj</strong> above and let that library call <strong>libpmem</strong> for them.</p>
> ```

Done.
___
*[`data/en/pmdk.yml` line 33 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaZ_qJEvpJpbpoi4ok:-Ncc0KQw-WSjpCrj4viC:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L33)):*
> ```YAML
>     library_item3:
>       title: 'libpmem2'
>       content: "<p>The <strong>libpmem2</strong> library provides low level persistent memory support. The library is a new version of <strong>libpmem</strong>. <strong>libpmem2</strong> provides a more universal and platform-agnostic interface. Developers wishing to roll their own persistent memory algorithms will find this library useful, but most developers will likely use <strong>libpmemobj</strong> above that provides memory allocation and transactions support.</p>
> ```

Done.
___
*[`data/en/pmdk.yml` line 35 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaZWpo-tibN-OTWhEr:-Ncc1sNdD83es3g4Ew49:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L35)):*
> ```YAML
>       content: "<p>The <strong>libpmem2</strong> library provides low level persistent memory support. The library is a new version of <strong>libpmem</strong>. <strong>libpmem2</strong> provides a more universal and platform-agnostic interface. Developers wishing to roll their own persistent memory algorithms will find this library useful, but most developers will likely use <strong>libpmemobj</strong> above that provides memory allocation and transactions support.</p>
>                 <p>See the <a href=\"./libpmem2\">libpmem2 page</a> for documentation and examples.</p>
>                 <blockquote><p><strong>Note:</strong>Support for experimental <strong>async</strong> functions is available only in the release 1.13.0 and before.</p></blockquote>"
> ```

Done.
___
*[`data/en/pmdk.yml` line 56 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-Ncb-BQG5PMWf1Hvl5Xx:-Ncc0OQh1JfL4GOjrCnN:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L56)):*
> ```YAML
> Discontinuation:
>   enable: true
>   title: 'Discontinuation of the project'
> ```

Done.
___
*[`data/en/pmdk.yml` line 59 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-Ncb-ZuHAH3z5aF3UXQM:-Ncc1ATbEbseHG9Dwkw1:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L59)):*
> ```YAML
>   lists:
>     branch_list1: 
>       content: "<p>The <strong>libpmemblk</strong>, <strong>libpmemlog</strong>, <strong>librpma</strong>, <strong>libpmemset</strong>, <strong>libvmem</strong>, <strong>librpmem</strong>, <strong>libvmemcache</strong>, <strong>pmdk-convert</strong>, <strong>libpmemobj-cpp</strong> and <strong>pmemkv</strong> libraries will no longer be maintained by Intel.</p>"
> ```

Done.
___
*[`data/en/pmdk.yml` line 70 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-Ncb-Xj_-iXOYMfewpWe:-Ncc1BxbEZ52eHHH-NWp:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L70)):*
> ```YAML
>                     maintain patches for the open source software community, please create your own fork of this project."
>         list_item4:
>           content: "You will find more information <a href=\"/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/\">here</a>."
> ```

Done.
___
*[`data/en/pmdk.yml` line 73 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-Ncb-n9_8j0U1Wvv7dFA:-Ncc1VgK6wcAMWC6xf-i:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L73)):*
> ```YAML
> 
>     branch_list2:
>       content: "<p>Support for <strong>Windows</strong> and <strong>FreeBSD</strong> are deprecated since <strong>PMDK 1.13.0</strong> release and will be removed in the <strong>PMDK 2.0.0</strong> release.</p>"
> ```

Done.
___
*[`data/en/pmdk.yml` line 79 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-Ncb0SRVE0f6dpp-QTDg:-Ncc1iFv5cTTLPzbBxJo:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/data/en/pmdk.yml#L79)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I believe this part is not used at all, is it?
</blockquote></details>

Done.
___
*[`themes/pmem-hugo/layouts/pmdk/list.html` line 25 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcaUUWEA_LtIvXMW1XX:-Ncc-2ieDAXpxDj3c5kV:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/21ff134095ffd550457427245930a500e680a4d5/themes/pmem-hugo/layouts/pmdk/list.html#L25)):*
> ```HTML
> 
> ```

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/367)* status: 32 of 33 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[`data/en/pmdk.yml` line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/367#-NcgCQjs6s5XrqgHL-AF:-Ncgkgtd3SEssi-bBT4q:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/49bd43aa52c37922ce7cbdd5ebb88540c529d9d8/data/en/pmdk.yml#L15)):*
> ```YAML
>   title: ''
>   content_banner:
>     bold_text: '<p>The <a href=\"https://github.com/pmem/pmdk/\">PMDK repository</a> on the GitHub is the ultimate source from release 2.0!</p>'
> ```

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/367#-:-NcgvzG3Ch5SpNtJJM6m:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
