### PR TITLE
pmdk: set Windows and FreeBSD support as deprecated

### PR DESCRIPTION
**Pull request by osalyk**
[pmem/pmdk](https://github.com/pmem/pmdk/pull/5553)
[pmem/pmdk](https://github.com/pmem/pmdk/pull/5557)

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/344)

### CODE REVIEW

**Comment by wlemkows** [comment]
Can you please put the link to the preview?

**Review by lukaszstolarczuk — COMMENTED** [review]
Since you're adding an extra branch_list, it seems there might be a small issue because of an error in `themes/pmem-hugo/layouts/pmdk/list.html` file.

I believe the `{{end}}` clause should be before `</div>` closing tag

https://github.com/pmem/pmem.github.io/blob/main/themes/pmem-hugo/layouts/pmdk/list.html#L34

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/344#-:-NRHlIfQ8I9pdmahrNqY:b-d014xc)* status: 0 of 6 files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/344#-:-NRcZ4f98XH1kK95AjWW:b-amkx4c)* status: 0 of 6 files reviewed, all discussions resolved

**Review by lukaszstolarczuk — APPROVED** [review]
FYI, preview's here: https://lukaszstolarczuk.github.io/pmdk/

:lgtm: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/344#-:-NRceIZUDhGKagic-nRT:b5h5m2l)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/344#-NRchXlf7wB3pB2QDsTm:-NRchXlg3MCVkzWNwZAD:b3w74zp) (no related file):*
heh, FYI, the small issue I pointed above still exists, but it seems that HTML is so cool it doesn't do much damage :smile: 

>Since you're adding an extra branch_list, it seems there might be a small issue because of an error in themes/pmem-hugo/layouts/pmdk/list.html file.
>
>I believe the {{end}} clause should be before </div> closing tag
>
>https://github.com/pmem/pmem.github.io/blob/main/themes/pmem-hugo/layouts/pmdk/list.html#L34
>

___

**Pull request merged**
