### PR TITLE
add blog post about dockers

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
Preview: https://lukaszstolarczuk.github.io/blog/2022/12/dockers-with-pmdk/

FYI, I just ran this through Grammarly, so I hope there shouldn't be any grammatic errors 😉 

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/315)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/315)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`content/blog/2022/dockers.md` line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRG3Ur0GLPoAv3aZq0:-NGRG3Ur0GLPoAv3aZq1:b-4q274z) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L38)):*
> ```Markdown
> [this overview](https://docs.docker.com/get-started/overview/). We use dockers in almost
> all of our repositories in pmem organization. In this blog post, I will describe
> how we use dockers based on [pmemkv](https://github.com/pmem/pmemkv) repository.
> ```

I'm not sure if using pmemkv as an example would be the best fit right now, but I started writing this blog post some time ago and am not sure if would make much difference...? for sure, it would require some re-organizing the flow of this post :wink:

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/315)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`content/blog/2022/dockers.md` line 12 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRGBEl8bjROo1F4C8M:-NGRGBEl8bjROo1F4C8N:bgxmyoi) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L12)):*
> ```Markdown
> 
> # Blog post description
> description: "A short story how we use dockers in PMDK"
> ```

A short story **on**
___
*[`content/blog/2022/dockers.md` line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRGftN8jL-wYEed7kE:-NGRGftN8jL-wYEed7kF:b-m4uf0e) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L38)):*
> ```Markdown
> [this overview](https://docs.docker.com/get-started/overview/). We use dockers in almost
> all of our repositories in pmem organization. In this blog post, I will describe
> how we use dockers based on [pmemkv](https://github.com/pmem/pmemkv) repository.
> ```

based on **the**
___
*[`content/blog/2022/dockers.md` line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRG3Ur0GLPoAv3aZq0:-NGRGxen2aARwzoWbMFD:bhe1zeh) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if using pmemkv as an example would be the best fit right now, but I started writing this blog post some time ago and am not sure if would make much difference...? for sure, it would require some re-organizing the flow of this post :wink: 
</blockquote></details>

Maybe it's not the best fit, but it's ok.
___
*[`content/blog/2022/dockers.md` line 50 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRI8us97LNl28ZySIi:-NGRI8us97LNl28ZySIj:bi2pqtg) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L50)):*
> ```Markdown
> images for commonly used Linux distributions. Each of our repositories contain `utils/docker`
> directory, like [here](https://github.com/pmem/pmemkv/tree/master/utils/docker). Images are stored
> in a separate sub-directory, unsurprisingly called `images`. Among docker 'recipes', there lay down some
> ```

docker 'recipes' **(Dockerfiles)**,
___
*[`content/blog/2022/dockers.md` line 91 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRP0vg6POredyZE43l:-NGRP0vg6POredyZE43m:b-7osgbq) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L91)):*
> ```Markdown
> 
> As I mentioned above, we keep all "docker" related files, in most of our repositories,
> in a `utils/docker` part of the tree. For example, in pmemkv it will be
> ```

it is



_Code quote:_
```Markdown
it will be
```
___
*[`content/blog/2022/dockers.md` line 99 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRPYZUCqkzq3gGYWg7:-NGRPYZUCqkzq3gGYWg8:bvnomi) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L99)):*
> ```Markdown
> * two helper scripts for building and pushing images to the "registry" (a.k.a. GitHub's Packages)
> 
> Dockerfiles 'recipes' are used by the helper scripts, and they, in turn, are used by the
> ```

**Dockerfile** 'recipes'



_Code quote:_
```Markdown
Dockerfiles 'recipes'
```
___
*[`content/blog/2022/dockers.md` line 100 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRPr0I7oXz9lbCPqNj:-NGRPr0I7oXz9lbCPqNk:bbp3p1v) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L100)):*
> ```Markdown
> 
> Dockerfiles 'recipes' are used by the helper scripts, and they, in turn, are used by the
> "upper" layer of scripts that reside directly in the `utils/docker` dir. `pull-or-rebuild-image.sh`
> ```

nit: directory



_Code quote:_
```Markdown
dir
```
___
*[`content/blog/2022/dockers.md` line 102 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRR49x2OL6WQtcSbVs:-NGRR49x2OL6WQtcSbVt:b-f9cx4y) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L102)):*
> ```Markdown
> "upper" layer of scripts that reside directly in the `utils/docker` dir. `pull-or-rebuild-image.sh`
> script makes use of these helpers. It decides whether to re-build the image or just download it
> from the registry. Images' re-building is based on changes, introduced by a user (e.g., in
> ```

This comma is not needed.



_Code quote:_
```Markdown
changes, introduced
```
___
*[`content/blog/2022/dockers.md` line 105 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRRIXc-iUuLgPZQ7tk:-NGRRIXc-iUuLgPZQ7tl:b2xm39n) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L105)):*
> ```Markdown
> a Pull Request).
> 
> In 'docker' directory, there are also located some `build*` scripts (usually just one `build.sh`)
> ```

**located** is not needed here



_Code quote:_
```Markdown
there are also located some `build*` scripts
```
___
*[`content/blog/2022/dockers.md` line 105 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRRq1jBqC4gt1Aa8Pq:-NGRRq1jBqC4gt1Aa8Pr:b1vlvkv) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L105)):*
> ```Markdown
> a Pull Request).
> 
> In 'docker' directory, there are also located some `build*` scripts (usually just one `build.sh`)
> ```

nit: I think it would be better to mention these main scripts first, and later describe helper scripts from the previous paragraph. But maybe it's just because that is the thing that I am interested most when getting familiar with these scripts.
___
*[`content/blog/2022/dockers.md` line 106 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRRadE6S6lzMHpFfSu:-NGRRadE6S6lzMHpFfSv:b-s8h8zc) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L106)):*
> ```Markdown
> 
> In 'docker' directory, there are also located some `build*` scripts (usually just one `build.sh`)
> and a few of `run-*`. The first one is used by our CI as an entry point to prepare the environment
> ```

(...) scripts.



_Code quote:_
```Markdown
a few of `run-*`
```
___
*[`content/blog/2022/dockers.md` line 111 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRSd-VCo8jvkcyJcNw:-NGRSd-VCo8jvkcyJcNx:bdp1mnb) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L111)):*
> ```Markdown
> 
> All GitHub Actions workflows and jobs (using the listed above scripts) are defined in
> `.github/workflows` sub-tree of our repositories. For pmemkv it will be
> ```

**it is** or perhaps **that would be here**



_Code quote:_
```Markdown
it will be
```

**Comment by lukaszstolarczuk** [comment]
I need to re-write this to be more PMDK-focused and rather ignore "soon to be old" repositories, like pmemkv 😉

**Review by pbalcer — CHANGES_REQUESTED** [review]
Grammarly doesn't think for you ;)
https://www.youtube.com/watch?v=Q5rB9jDbTPU

I agree, don't reference repos/projects that are going to be archived soon.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/315#-:-NGRcE2IEBvBWw6wtsLF:bhe8ul1)* status: 0 of 1 files reviewed, 16 unresolved discussions (waiting on @lukaszstolarczuk and @PatKamin)

___
*[`content/blog/2022/dockers.md` line 12 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRcUik4wkQKpQSGmVW:-NGRcUik4wkQKpQSGmVX:b22ddo) ([raw file](https://github.com/pmem/pmem.github.io/blob/77ef6c73d5fdc1bb1b848c8a1341b4da31516523/content/blog/2022/dockers.md#L12)):*
> ```Markdown
> 
> # Blog post description
> description: "A short story how we use dockers in PMDK"
> ```

A short story is a literary term that usually means prose writing, typically fiction.

I  understand the colloquial use here, but it just doesn't fit here IMHO ;)
___
*[`content/blog/2022/dockers.md` line 46 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRdDfI2w0ztm3Xp07d:-NGRdDfI2w0ztm3Xp07e:bsb5mvc) ([raw file](https://github.com/pmem/pmem.github.io/blob/77ef6c73d5fdc1bb1b848c8a1341b4da31516523/content/blog/2022/dockers.md#L46)):*
> ```Markdown
> # Dockers are easy and maintainable
> 
> From our point of view, dockers provide a significant simplification of part of our work.
> ```

dockers significantly simplify part 
___
*[`content/blog/2022/dockers.md` line 120 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRevG78sqhQemH2p59:-NGRevG78sqhQemH2p5A:bty1t67) ([raw file](https://github.com/pmem/pmem.github.io/blob/77ef6c73d5fdc1bb1b848c8a1341b4da31516523/content/blog/2022/dockers.md#L120)):*
> ```Markdown
> have forced teams to update testing workflows accordingly to their needs. Some changes to CI and
> dockers were introduced in a rush (e.g., because of some deadlines) and were not ported to other
> repositories. Having said that, we tried to keep the differences to the minimum and level as many
> ```

"keep the differences ... level" ?

That last sentence is odd.
___
*[`content/blog/2022/dockers.md` line 144 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRfLTF2qFaNTM9H68w:-NGRfLTF2qFaNTM9H68x:b-xon2gp) ([raw file](https://github.com/pmem/pmem.github.io/blob/77ef6c73d5fdc1bb1b848c8a1341b4da31516523/content/blog/2022/dockers.md#L144)):*
> ```Markdown
> working in our CI! As I described above, there are multiple benefits of introducing them
> into our development process, with "reproducible" and "portability" as one of the greatest
> (in my opinion). In overall, they add a little complexity to our workflows, but after
> ```

drop 'in'.

**Review by pbalcer — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/315)* status: all files reviewed (commit messages unreviewed), 19 unresolved discussions (waiting on @lukaszstolarczuk and @PatKamin)

___
*[`content/blog/2022/dockers.md` line 120 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRevG78sqhQemH2p59:-NJjglcnBndQ__oQPcSW:b-r0fjp8) ([raw file](https://github.com/pmem/pmem.github.io/blob/77ef6c73d5fdc1bb1b848c8a1341b4da31516523/content/blog/2022/dockers.md#L120)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`level` is used here as a verb...
perhaps I should re-phrase it like:
`keep the differences ... and level/even out`
</blockquote></details>

I would just remove "and level" entirely
___
*[`content/blog/2022/dockers.md` line 35 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjbmTF0UmM6Wkz_ToA:-NJjbmTF0UmM6Wkz_ToB:b-8vyj9r) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L35)):*
> ```Markdown
> 
> In this blog post, I'll describe why we believe dockers are easy to use, time-saving, and very
> useful. If you have never heard of dockers (or containers in general), please read, for example,
> ```

useful for ... ?
___
*[`content/blog/2022/dockers.md` line 37 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjbxJhB2gPxyMi6vJ3:-NJjbxJhB2gPxyMi6vJ4:b-32d1qd) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L37)):*
> ```Markdown
> useful. If you have never heard of dockers (or containers in general), please read, for example,
> [this overview](https://docs.docker.com/get-started/overview/). We use dockers in almost
> all of our repositories in our organization. In this blog post, I will describe how we use
> ```

`all of the repositories in our organization` or just `all of our repositories`
___
*[`content/blog/2022/dockers.md` line 50 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjfNFW1PaYweOPoko3:-NJjfNFXAHPQtv2Nkf9j:bb1bq0n) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L50)):*
> ```Markdown
> directory, like [here](https://github.com/pmem/pmdk/tree/master/utils/docker). Images are stored usually
> in a separate sub-directory - unsurprisingly called `images`. Among docker 'recipes' (Dockerfiles),
> there lay down some scripts used within containers to install dependencies (e.g., `install-valgrind.sh`)
> ```

lay down?

`there are some scripts` ?
___
*[`content/blog/2022/dockers.md` line 58 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjfjn66-1kpI6Z1tFz:-NJjfjn66-1kpI6Z1tG-:bz62sxr) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L58)):*
> ```Markdown
> # Cleaner workflow and reproducible environment
> 
> We figured that keeping Linux images as files simplifies their maintenance and updates, makes them
> ```

linux images? did you mean linux docker recipes?
___
*[`content/blog/2022/dockers.md` line 63 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjfscNDBFfcNRkvJ8b:-NJjfscNDBFfcNRkvJ8c:bb28u4x) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L63)):*
> ```Markdown
> is just the beginning. If the CI fails, you have to dig through the CI's logs and try to guess what
> happened. With a quickly reproducible environment, the job got a lot easier. We don't have to look
> for a specific machine with some precise version of a Linux distribution. We read our README ;-)
> ```

we -> just?
___
*[`content/blog/2022/dockers.md` line 83 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjg6GU31E-4KNmybL0:-NJjg6GU31E-4KNmybL1:b-mf18av) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L83)):*
> ```Markdown
> either `pull` the image and just run it or use it as a base image for your own Dockerfile 'recipe'.
> Building on top of our image gives you the advantage of having all dependencies already prepared.
> Such an image would have to be expended with potential custom packets and files, e.g., for further
> ```

packets?
___
*[`content/blog/2022/dockers.md` line 117 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjg_He1Fp-n5owkBAt:-NJjg_He1Fp-n5owkBAu:bbmjgfe) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L117)):*
> ```Markdown
> 
> As I wrote in the introduction, not all repositories are handled exactly the same. Each repository
> in related to PMem was developed by various people with heads full of ideas. Some requirements may
> ```

in related?
___
*[`content/blog/2022/dockers.md` line 151 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjh2BL5wBrKgF20xWB:-NJjh2BL5wBrKgF20xWC:b-zca8j9) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L151)):*
> ```Markdown
> To summarize dockers' usage in PMDK, I'd have to say: it's very nice to have them
> working in our CI! As I described above, there are multiple benefits of introducing them
> into our development process, with "reproducible" and "portability" as one of the greatest
> ```

reproducibility

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/315)* status: 0 of 1 files reviewed, 18 unresolved discussions (waiting on @PatKamin and @pbalcer)

___
*[`content/blog/2022/dockers.md` line 105 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRRq1jBqC4gt1Aa8Pq:-NJjlEzSAP1I0ZyUo39Q:bvsxdi9) ([raw file](https://github.com/pmem/pmem.github.io/blob/22994d68fcb231db007656deebcf64a28edfdc16/content/blog/2022/dockers.md#L105)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: I think it would be better to mention these main scripts first, and later describe helper scripts from the previous paragraph. But maybe it's just because that is the thing that I am interested most when getting familiar with these scripts.
</blockquote></details>

I re-wrote it a little, but I think it reads from the bottom to the top. From dockers, building images, tests' runners, to CI workflows.
___
*[`content/blog/2022/dockers.md` line 120 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NGRevG78sqhQemH2p59:-NJjmmsd6KuZJc-mEWQi:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/77ef6c73d5fdc1bb1b848c8a1341b4da31516523/content/blog/2022/dockers.md#L120)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I would just remove "and level" entirely
</blockquote></details>

Done.
___
*[`content/blog/2022/dockers.md` line 35 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjbmTF0UmM6Wkz_ToA:-NJjjf3B7rRCIZS4zTLx:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L35)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

useful for ... ?
</blockquote></details>

Done.
___
*[`content/blog/2022/dockers.md` line 37 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjbxJhB2gPxyMi6vJ3:-NJjjw4z7_meGbnEn3JJ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L37)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

`all of the repositories in our organization` or just `all of our repositories`
</blockquote></details>

Done.
___
*[`content/blog/2022/dockers.md` line 50 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjfNFW1PaYweOPoko3:-NJjk3-Y4CDabI3wA0eT:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L50)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

lay down?

`there are some scripts` ?
</blockquote></details>

Done.
___
*[`content/blog/2022/dockers.md` line 58 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjfjn66-1kpI6Z1tFz:-NJjkRWW2sskSvMBqUh9:bvfrn3v) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L58)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

linux images? did you mean linux docker recipes?
</blockquote></details>

I meant Linux images - I added `""` and made it more explicit these are **Docker** files
___
*[`content/blog/2022/dockers.md` line 63 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjfscNDBFfcNRkvJ8b:-NJjkolQ9S3Q9k2ES93c:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L63)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

we -> just?
</blockquote></details>

Done.
___
*[`content/blog/2022/dockers.md` line 83 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjg6GU31E-4KNmybL0:-NJjl2GQ0vm66lkqtQZt:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L83)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

packets?
</blockquote></details>

Done.
___
*[`content/blog/2022/dockers.md` line 117 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjg_He1Fp-n5owkBAt:-NJjmfhj-r3VZYUKfSdr:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L117)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

in related?
</blockquote></details>

Done.
___
*[`content/blog/2022/dockers.md` line 151 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/315#-NJjh2BL5wBrKgF20xWB:-NJjmr7k3TrJs_bauIhG:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/48742173bb277bd942c8481287076aff897b69e7/content/blog/2022/dockers.md#L151)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

reproducibility 
</blockquote></details>

Done.

**Review by pbalcer — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/315#-:-NJk-xqe9d8Ic_ZP9lWv:bnfp4nl)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @PatKamin)

**Pull request merged**
