### PR TITLE
add PMDK release blog

### PR DESCRIPTION
**Pull request by pbalcer**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/113)

### CODE REVIEW

**Comment by George330** [comment]
___
*[_posts/2019-10-11-release-1-7.md, line 21 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/113#-Ls12fAe6k3MnmKaEbf7:-Ls12fAe6k3MnmKaEbf8:b-qtawz6) ([raw file](https://github.com/pmem/pmem.github.io/blob/27eb8a76f61cbbb8359b92ec0346a6d0d05a687a/_posts/2019-10-11-release-1-7.md#L21)):*
> ```
> We realized that large amounts of
> software doesn't need 
> ```
don't

**Comment by George330** [comment]
___
*[_posts/2019-10-11-release-1-7.md, line 23 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/113#-Ls13eq8BLD5N1_fQhjs:-Ls13eq8BLD5N1_fQhjt:be4k6ox) ([raw file](https://github.com/pmem/pmem.github.io/blob/27eb8a76f61cbbb8359b92ec0346a6d0d05a687a/_posts/2019-10-11-release-1-7.md#L23)):*
> ```
> it just
> wants a convenient way to store objects in a manner that's simple
> ```
it sounds a bit off... it implies that a code has feelings and desires and that is not true. Humans do. Anthropomorphism is a recurring theme in your style of writing. ;)

**Comment by George330** [comment]
___
*[_posts/2019-10-11-release-1-7.md, line 78 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/113#-Ls1A9Kd5FLdkPZK0EW4:-Ls1A9Kd5FLdkPZK0EW5:b-dt044v) ([raw file](https://github.com/pmem/pmem.github.io/blob/27eb8a76f61cbbb8359b92ec0346a6d0d05a687a/_posts/2019-10-11-release-1-7.md#L78)):*
> ```
> In select workloads
> ```
selected

**Comment by George330** [comment]
___
*[_posts/2019-10-11-release-1-7.md, line 85 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/113#-Ls1ASMZ9Hcl0kzMySHJ:-Ls1ASMZ9Hcl0kzMySHK:bfh9m26) ([raw file](https://github.com/pmem/pmem.github.io/blob/27eb8a76f61cbbb8359b92ec0346a6d0d05a687a/_posts/2019-10-11-release-1-7.md#L85)):*
> ```
> We've received feedback about `pmemobj_reserve()` function that its performance
> degrades significantly once the number of actions gets large. This made sense,
> ```
We've received feedback about `pmemobj_reserve()` function. Its performance
> degrades significantly once the number of actions becomes large.

**Comment by George330** [comment]
___
*[_posts/2019-10-11-release-1-7.md, line 114 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/113#-Ls1BP7x80puEHRWZ5Xy:-Ls1BP7x80puEHRWZ5Xz:b7pc2gd) ([raw file](https://github.com/pmem/pmem.github.io/blob/27eb8a76f61cbbb8359b92ec0346a6d0d05a687a/_posts/2019-10-11-release-1-7.md#L114)):*
> ```
> And so to solve the above problem
> ```
above - adv
you need an adj 
or displace the adverb into its proper position

**Comment by George330** [comment]
___
*[_posts/2019-10-11-release-1-7.md, line 134 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/113#-Ls1C6FsDeZNgSbW8aM-:-Ls1C6FsDeZNgSbW8aM0:bvnca48) ([raw file](https://github.com/pmem/pmem.github.io/blob/27eb8a76f61cbbb8359b92ec0346a6d0d05a687a/_posts/2019-10-11-release-1-7.md#L134)):*
> ```
> and the flush operations simply schedules and initiates the transfer
> ```
schedule.... initiate...

**Comment by George330** [comment]
___
*[_posts/2019-10-11-release-1-7.md, line 138 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/113#-Ls1CONSBz5tcTsU3ll6:-Ls1CONSBz5tcTsU3ll7:b-d431wd) ([raw file](https://github.com/pmem/pmem.github.io/blob/27eb8a76f61cbbb8359b92ec0346a6d0d05a687a/_posts/2019-10-11-release-1-7.md#L138)):*
> ```
> memory, can also
> ```
a comma not needed

**Comment by George330** [comment]
___
*[_posts/2019-10-11-release-1-7.md, line 144 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/113#-Ls1CXwq2IEPnJwsjyod:-Ls1CXwq2IEPnJwsjyoe:b-21y6kf) ([raw file](https://github.com/pmem/pmem.github.io/blob/27eb8a76f61cbbb8359b92ec0346a6d0d05a687a/_posts/2019-10-11-release-1-7.md#L144)):*
> ```
> With this PMDK release done
> ```
"done" is redundant

**Comment by kilobyte** [comment]
@George330 : this pull request has already been merged, you'd need to open a new one with corrections.

**Pull request merged**
