### PR TITLE
Increase table readability in pmdk article

### PR DESCRIPTION
**Pull request by osalyk**
https://osalyk.github.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/319)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
dream comes true, I had this fix on my TODO list :smiley: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/319#-:-NKSTi5TDglFCS8YwL7Y:b-bb5eie)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/319#-NKSTq6B2ts3JFicFS0k:-NKSTq6B2ts3JFicFS0l:b-9sha91) (no related file):*
can you enable your own fork and push your changes to your main branch, so we could see the rendered version on https://osalyk.github.io/

___
___
*[`content/blog/2022/update-pmdk-project-status.md` line 64 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/319#-NKSTTtlCTZUEA6i2YEJ:-NKSTTtlCTZUEA6i2YEK:b-n0lcaz) ([raw file](https://github.com/pmem/pmem.github.io/blob/0b536d24f3d0551b3528e987c1791908228c7c37/content/blog/2022/update-pmdk-project-status.md#L64)):*
> ```Markdown
> | libpmem libpmem2 libpmemobj libpmempool pmempool pmreorder | https://github.com/pmem/pmdk | Issue Reporting and Bug Fixes via GitHub and pmdk_support@intel.com  Release planned for Crow Pass |
> | valgrind pmemcheck | https://github.com/pmem/valgrind | Issue Reporting and Bug Fixes via GitHub and pmdk_support@intel.com  Release planned for Crow Pass |
> | libmemkind<br /> TieredMemDB | https://github.com/memkind/memkind<br /> https://github.com/TieredMemDB | Issue Reporting and Bug Fixes via GitHub and pmdk_support@intel.com |
> ```

I believe, instead of `<br />` you can simple write `\` (md syntax should parse this as new line)
___
*[`content/blog/2022/update-pmdk-project-status.md` line 67 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/319#-NKSTL10EoOaELyYkz5k:-NKSTL11142QFpncOsfr:bi5rg2s) ([raw file](https://github.com/pmem/pmem.github.io/blob/0b536d24f3d0551b3528e987c1791908228c7c37/content/blog/2022/update-pmdk-project-status.md#L67)):*
> ```Markdown
> | PMUL<br /> LLPL<br /> PCJ | https://github.com/pmem/pmul<br /> https://github.com/pmem/llpl<br /> https://github.com/pmem/pcj | Issue Reporting and Bug Fixes via GitHub and pmdk_support@intel.com  Intel JAVA Team Maintaining |
> | ndctl | https://github.com/pmem/ndctl | Issue Reporting and Bug Fixes via GitHub and pmdk_support@intel.com  Intel Linux Kernel Team Maintaining and continuing development for CXL-based memory devices & NVDIMMs |
> | librpma | https://github.com/pmem/rpma | Issue Reporting and Bug Fixes via GitHub and pmdk_support@intel.com  Seeking new co-maintainer(s) to continue development towards production release |
> ```

I think a few more `br` could be added, like between "issue reporting..." and "Seeking new co-maint..." (and some more)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/319)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/319#-NKSTq6B2ts3JFicFS0k:-NKTdQd2ErOBRsuJKCJQ:b-q9fftg) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can you enable your own fork and push your changes to your main branch, so we could see the rendered version on https://osalyk.github.io/
</blockquote></details>

https://osalyk.github.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/

___
___
*[`content/blog/2022/update-pmdk-project-status.md` line 64 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/319#-NKSTTtlCTZUEA6i2YEJ:-NKTdT9LDsMnXRZsyqAp:b-z9im6) ([raw file](https://github.com/pmem/pmem.github.io/blob/0b536d24f3d0551b3528e987c1791908228c7c37/content/blog/2022/update-pmdk-project-status.md#L64)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe, instead of `<br />` you can simple write `\` (md syntax should parse this as new line)
</blockquote></details>

It doesn't work in some markdown applications
___
*[`content/blog/2022/update-pmdk-project-status.md` line 67 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/319#-NKSTL10EoOaELyYkz5k:-NKTh-ze9VSJbHTH0YQk:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0b536d24f3d0551b3528e987c1791908228c7c37/content/blog/2022/update-pmdk-project-status.md#L67)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think a few more `br` could be added, like between "issue reporting..." and "Seeking new co-maint..." (and some more)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
hmm I wished we could make it somehow with a border... e.g. like the table here: https://pmem.io/pmemkv/

But I guess it may not be easily achievable, since we're using MD style...

I found a solution online using an additional p/div/... element with a class and, of course, our custom.css file (static/css/custom.css), but I haven't tested it and am not sure if you can embed the table inside of the div
```
<p class="myclass">

<put md table here>

</p>
```

Perhaps you have a better idea or perhaps we just ignore my problem with that :wink: :smile: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/319#-:-NKTnECm8ZjG558_eL7B:bxq2kv8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/319#-:-NKXGxYI9s3nIl8rHznQ:bvwfphi)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/319#-:-NKXPzOI4QYlaRX4NE6R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by lukaszstolarczuk — COMMENTED** [review]
you are my hero :smile: 

2 small (potential) issues from my side; beside that it looks great

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/319#-:-NKr5TpN2Hy0vGfxpfAx:b-rbtr4d)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[`content/blog/2022/update-pmdk-project-status.md` line 63 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/319#-NKr5Bqa87mt7FH-bmkj:-NKr5Bqa87mt7FH-bmkk:b-rkrhb) ([raw file](https://github.com/pmem/pmem.github.io/blob/0d7cd2d0be002724c75afb7a3e896c2324eae7c5/content/blog/2022/update-pmdk-project-status.md#L63)):*
> ```Markdown
> | Library | URL | Support Summary |
> |---|---|---|
> | libpmem libpmem2 libpmemobj libpmempool pmempool pmreorder | https://github.com/pmem/pmdk | Issue Reporting and Bug Fixes via GitHub and pmdk_support@intel.com<br /> Release planned for Crow Pass |
> ```

also consider `<br />` between all these libraries/tools
___
*[`content/blog/2022/update-pmdk-project-status.md` line 64 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/319#-NKr5Gux07VtFUf1BtHE:-NKr5Gux07VtFUf1BtHF:b-wtwt2m) ([raw file](https://github.com/pmem/pmem.github.io/blob/0d7cd2d0be002724c75afb7a3e896c2324eae7c5/content/blog/2022/update-pmdk-project-status.md#L64)):*
> ```Markdown
> |---|---|---|
> | libpmem libpmem2 libpmemobj libpmempool pmempool pmreorder | https://github.com/pmem/pmdk | Issue Reporting and Bug Fixes via GitHub and pmdk_support@intel.com<br /> Release planned for Crow Pass |
> | valgrind pmemcheck | https://github.com/pmem/valgrind | Issue Reporting and Bug Fixes via GitHub and pmdk_support@intel.com<br /> Release planned for Crow Pass |
> ```

same here, one extra *br* between valgrind and pmemcheck

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/319)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @grom72 and @lukaszstolarczuk)

___
*[`content/blog/2022/update-pmdk-project-status.md` line 63 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/319#-NKr5Bqa87mt7FH-bmkj:-NKrKV2y44D4IDpMf1-Y:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0d7cd2d0be002724c75afb7a3e896c2324eae7c5/content/blog/2022/update-pmdk-project-status.md#L63)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

also consider `<br />` between all these libraries/tools
</blockquote></details>

Done.
___
*[`content/blog/2022/update-pmdk-project-status.md` line 64 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/319#-NKr5Gux07VtFUf1BtHE:-NKrKXKv1O5lNe4Hk25d:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0d7cd2d0be002724c75afb7a3e896c2324eae7c5/content/blog/2022/update-pmdk-project-status.md#L64)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

same here, one extra *br* between valgrind and pmemcheck
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/319#-:-NKrZxrm5DvwVLNvU6bw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
