### PR TITLE
rpma: use MD-style links

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/225)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/225)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/225)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[content/rpma/documentation/basic-direct-write-to-pmem.md, line 35 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/225#-Mz-Vthc0sp1q6f2oePa:-Mz-Vthc0sp1q6f2oePb:b-tsfmxt) ([raw file](https://github.com/pmem/pmem.github.io/blob/8cd715f858d301a151130cf59d8e5f174c869468/content/rpma/documentation/basic-direct-write-to-pmem.md#L35)):*
> ```Markdown
> You can finding the PCIe Root Port of the network interface knowing its producer and model in a single query:
> 
> ``` cmd
> ```

```cmd
```




_Code quote:_
```Markdown
``` cmd
```
___
*[content/rpma/documentation/basic-hw_sw_setup_starting_point.md, line 54 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/225#-Mz-WBONElYX6Jl3AePr:-Mz-WBONElYX6Jl3AePs:bu5vaoz) ([raw file](https://github.com/pmem/pmem.github.io/blob/8cd715f858d301a151130cf59d8e5f174c869468/content/rpma/documentation/basic-hw_sw_setup_starting_point.md#L54)):*
> ```Markdown
> Intel technologies may require enabled hardware, software or service activation.
> 
> Intel disclaims all express and implied warranties, including without limitation, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement, as well as any warranty arising from course of performance, course of dealing, or usage in trade.
> ```

Missing EOL



_Code quote:_
```Markdown
 trade.
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/225)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[content/rpma/documentation/basic-direct-write-to-pmem.md, line 35 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/225#-Mz-Vthc0sp1q6f2oePa:-Mz-X4FY4BBu9xQoH4K6:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/8cd715f858d301a151130cf59d8e5f174c869468/content/rpma/documentation/basic-direct-write-to-pmem.md#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```cmd
```

</blockquote></details>

Done.
___
*[content/rpma/documentation/basic-hw_sw_setup_starting_point.md, line 54 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/225#-Mz-WBONElYX6Jl3AePr:-Mz-Wpb08RIraFZ4scDt:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/8cd715f858d301a151130cf59d8e5f174c869468/content/rpma/documentation/basic-hw_sw_setup_starting_point.md#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Missing EOL
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/225#-:-Mz-XWdiDUfj8c-Cmrf_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/225)* status: all files reviewed, 1 unresolved discussion

___
*[content/rpma/documentation/basic-direct-write-to-pmem.md, line 54 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/225#-MzF5kiO1f7LYR3dNYFp:-MzF5kiPBh2ALpimSjVI:b-8h44g6) ([raw file](https://github.com/pmem/pmem.github.io/blob/d9203c1c0c4662b97ce366474e88d86c48a27be0/content/rpma/documentation/basic-direct-write-to-pmem.md#L54)):*
> ```Markdown
> ```
> 
> The `1` at the end of the output in this case means the DDIO feature is turned on for this PCIe Root Port which is the default for the **Cascade Lake** platforms. In this case, it is required to turn it off for each **Cascade Lake** system with PMem if you want to have Direct Write to PMem capability via RDMA. For details please see [rpma_peer_cfg_set_direct_write_to_pmem(3)](https://pmem.io/rpma/manpages/master/rpma_peer_cfg_set_direct_write_to_pmem.3) and [rpma_flush(3)](https://pmem.io/rpma/manpages/master/rpma_flush.3).
> ```

I believe you can drop `https://pmem.io` part :wink:

**Pull request merged**
