### PR TITLE
add miniasync blog post

### PR DESCRIPTION
**Pull request by pbalcer**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/207)

### CODE REVIEW

**Comment by pbalcer** [comment]
First draft. I'll add pictures and an editing pass on Monday. I initially wanted to also describe the pmem2 pmdk integration plans and a pmemblk example, but the post was getting too long. (And we don't have the pmem2 integration done yet :P)

Preview: https://pbalcer.github.io/blog/2022/02/leveraging-asynchronous-hardware-accelerators-for-fun-and-profit/

**Comment by kswiecicki** [comment]
___
*[content/blog/2022/async.md, line 69 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzTz9O8Xj37mm-IiV0:-MwzTz9O8Xj37mm-IiV1:b-6tvakm) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L69)):*
> ```Markdown
> 
> DSA enables user-space software to quickly and efficiently perform a background
> memory operation. Among supported supported operations are
> ```

`Supported` once.



_Code quote:_
```Markdown
Among supported supported
```

**Comment by kswiecicki** [comment]
___
*[content/blog/2022/async.md, line 101 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzUVej01CW69ElvHsj:-MwzUVej01CW69ElvHsk:bapiw0) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L101)):*
> ```Markdown
> ## Data Mover Library
> 
> Using DSA directly can be quite involved. But most developers won't have to
> ```

[...] be quite involving.



_Code quote:_
```Markdown
quite involved
```

**Comment by kswiecicki** [comment]
___
*[content/blog/2022/async.md, line 227 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzW5oU7ROAqQP61_L3:-MwzW5oU7ROAqQP61_L4:bu9sdnp) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L227)):*
> ```Markdown
> What we ended up creating is somewhere in between - [libminiasync][miniasync-github].
> 
> ## lbiminiasync
> ```

libminiasync



_Code quote:_
```Markdown
lbiminiasync
```

**Comment by kswiecicki** [comment]
___
*[content/blog/2022/async.md, line 236 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzWI9RD5Ai6LtvdyRI:-MwzWI9RD5Ai6LtvdyRJ:b34nszt) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L236)):*
> ```Markdown
> was originally implemented using miniasync.
> 
> And no relaying dark arts :)
> ```

relaying on



_Code quote:_
```Markdown
And no relaying dark arts :)
```

**Comment by kswiecicki** [comment]
___
*[content/blog/2022/async.md, line 236 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzWI9RD5Ai6LtvdyRI:-MwzXiSb1W6nGCE27VRt:bzgfx0z) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L236)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

relaying on
</blockquote></details>

relying on* actually

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/207)* status: all files reviewed, 18 unresolved discussions (waiting on @pbalcer)

___
*[content/blog/2022/async.md, line 6 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzshZb4Ptu5aUHq2rO:-MwzshZb4Ptu5aUHq2rP:b-gu3kbn) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L6)):*
> ```Markdown
> 
> # Blog post creation date
> date: 2022-02-21T15:20:43+01:00
> ```

update the date, I guess
___
*[content/blog/2022/async.md, line 28 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzsGaPDOSuxEsDCywH:-MwzsGaQ8BzP6Qr1AacH:be3qsz1) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L28)):*
> ```Markdown
> blogs: ['PMDK']
> # Blog tags
> tags: ["miniasync", "pmem2", "DML", "DSA", "concurrency", "async", "asynchronous"]
> ```

"pmem2"?
___
*[content/blog/2022/async.md, line 45 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzaveV30elotN8-rP2:-MwzaveV30elotN8-rP3:b-cdfp9y) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L45)):*
> ```Markdown
> throughputs. This led to software being optimized for concurrent access to the
> storage devices, either directly through the use of asynchronous APIs such as
> io_uring or by indirectly by relaying on kernel's builtin mechanisms such as
> ```

`or indirectly` (drop first `by`)
___
*[content/blog/2022/async.md, line 57 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzciEX1wrceNNtbZ_K:-MwzciEX1wrceNNtbZ_L:byemls6) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L57)):*
> ```Markdown
> in benchmarks, but at the cost of increased CPU utilization.
> 
> Now, you can optimize certainly software by changing it to use a more
> ```

`you can certainly optimize`
___
*[content/blog/2022/async.md, line 64 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mwzd8K6Cz0cEvygJg5E:-Mwzd8K6Cz0cEvygJg5F:b-k8km01) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L64)):*
> ```Markdown
> Thankfully, starting in the next generation Xeon (Sapphire Rapids), the
> platform will gain the ability to offload some of its memory operations through
> the use of a builtin DMA engine - [Intel Data Streaming Accelerator (Intel DSA)][intel-dsa].
> ```

`INTEL®` (?)
___
*[content/blog/2022/async.md, line 80 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzhenzBpXAvvoNq2mC:-MwzhenzBpXAvvoNq2mD:b-baz0pj) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L80)):*
> ```Markdown
> applications can access each work queue by mapping a special character device
> exposed by the kernel. This map can then be used to directly submit work using
> specialized instructions, MOVDIR64b or ENQCMD.
> ```

surround these instructions with
```
`
```
___
*[content/blog/2022/async.md, line 87 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwziOew4H0p3o3YLH1t:-MwziOew4H0p3o3YLH1u:b-1267fj) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L87)):*
> ```Markdown
> address. Software can also optionally request completion interrupt,
> but user-space applications will need to carefully weigh the costs of using
> such approach. Especially in the case of smallish transfers.
> ```

small/smaller (?) transfers
___
*[content/blog/2022/async.md, line 145 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzmLBO2Dc42gldyKTi:-MwzmLBO2Dc42gldyKTj:bscrnig) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L145)):*
> ```Markdown
> ```
> 
> > A C++ version is also available. See the [DML github][dml-github] page for details
> ```

`for details.` (pls add full stop)
___
*[content/blog/2022/async.md, line 154 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mwzmn3P2V9-tsB_gq4A:-Mwzmn3P2V9-tsB_gq4B:bb247hf) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L154)):*
> ```Markdown
> ## The async ecosystem
> 
> Contemporary software is used to dealing with asynchronous I/O devices. Be it
> ```

`is used to deal with`
___
*[content/blog/2022/async.md, line 241 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mwzq7bl2nQZlKQg3zbn:-Mwzq7bl2nQZlKQg3zbo:bqciv5) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L241)):*
> ```Markdown
> 
> Our new library, libminiasync, accomplishes those goals by providing a minimal
> abstraction of a `future` that represents an asynchronous task. At it's very core,
> ```

`At its very core`
___
*[content/blog/2022/async.md, line 281 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzquI1CzG4tGcr4D2A:-MwzquI1CzG4tGcr4D2B:bijgdhd) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L281)):*
> ```Markdown
> ```
> 
> > Based on the ['basic'][basic-example] miniasync example
> ```

`example.`
___
*[content/blog/2022/async.md, line 322 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzrXuF8Syp2W-Vb2cq:-MwzrXuF8Syp2W-Vb2cr:bavlcv8) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L322)):*
> ```Markdown
> a virtual data mover (vdm) abstraction.
> 
> ```
> ```

 \```C
___
*[content/blog/2022/async.md, line 350 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzzVVY0zF_mGhb6tVH:-MwzzVVY0zF_mGhb6tVI:bqfae77) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L350)):*
> ```Markdown
> with libpmem2 and the plans for integration in the rest of PMDK. We will also
> circle back to the block storage on PMem problem that I started with by exploring
> an example implementation of asynchronous pmemblk operations.
> ```

FYI, not sure if that's relevant - you didn't mention `pmemblk` at the beginning
___
*[content/blog/2022/async.md, line 352 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mx-0QMs2fDUMUEoZ4jt:-Mx-0QMs2fDUMUEoZ4ju:bauxevr) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L352)):*
> ```Markdown
> an example implementation of asynchronous pmemblk operations.
> 
> ## References
> ```

these links below are not displayed right now, so this section seems redundant.

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/207)* status: all files reviewed, 15 unresolved discussions (waiting on @kswiecicki and @lukaszstolarczuk)

___
*[content/blog/2022/async.md, line 28 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzsGaPDOSuxEsDCywH:-Mx-28jP-HVw_KkdH-TK:b-w8nf2f) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"pmem2"?
</blockquote></details>

well, miniasync's first use is going to be in pmem2 ;) I originally planned to write about it but decided to just write another blog post once we actually have it done.
___
*[content/blog/2022/async.md, line 45 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzaveV30elotN8-rP2:-Mx-2UVn5l5Y84Cho0zB:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`or indirectly` (drop first `by`)
</blockquote></details>

Done.
___
*[content/blog/2022/async.md, line 57 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzciEX1wrceNNtbZ_K:-Mx-2X698Dy0hLnySdmx:bb7f2mf) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`you can certainly optimize`
</blockquote></details>

done
___
*[content/blog/2022/async.md, line 64 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mwzd8K6Cz0cEvygJg5E:-Mx-2dTC1p7xV9VmT_CE:bb7f2mf) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L64)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`INTEL®` (?)
</blockquote></details>

done
___
*[content/blog/2022/async.md, line 69 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzTz9O8Xj37mm-IiV0:-Mx-2lJB9ofbX_X5UJdY:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L69)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

`Supported` once.
</blockquote></details>

Done.
___
*[content/blog/2022/async.md, line 80 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzhenzBpXAvvoNq2mC:-Mx-2oFu-XHO_wxq6q8A:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L80)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

surround these instructions with
```
`
```
</blockquote></details>

Done.
___
*[content/blog/2022/async.md, line 101 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzUVej01CW69ElvHsj:-Mx-2xmW42QdvbgnkJfi:biy15g3) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L101)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

[...] be quite involving.
</blockquote></details>

no, I think "can be quite involved" is the correct phrase.
___
*[content/blog/2022/async.md, line 145 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzmLBO2Dc42gldyKTi:-Mx-35tA8bxMJpi9dI9K:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L145)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`for details.` (pls add full stop)
</blockquote></details>

Done.
___
*[content/blog/2022/async.md, line 154 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mwzmn3P2V9-tsB_gq4A:-Mx-3JxDEz_nQ6KkTm-M:b3361xn) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L154)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`is used to deal with`
</blockquote></details>

I think that would change the meaning of the sentence. I meant that programmers know how to create software that uses async stuff. Not that some arbitrary "software" that is utilized to do async. Po naszemu: "software jest przyzwyczajony do", nie "software jest używany do".
___
*[content/blog/2022/async.md, line 227 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzW5oU7ROAqQP61_L3:-Mx-3mwe59lbK0JN_b7N:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L227)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

libminiasync
</blockquote></details>

Done.
___
*[content/blog/2022/async.md, line 236 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzWI9RD5Ai6LtvdyRI:-Mx-4V5lCLntY6I05qXh:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L236)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

relying on* actually
</blockquote></details>

Done.
___
*[content/blog/2022/async.md, line 241 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mwzq7bl2nQZlKQg3zbn:-Mx-4YNsCtFa2Hlt27Ku:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L241)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`At its very core`
</blockquote></details>

Done.
___
*[content/blog/2022/async.md, line 281 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzquI1CzG4tGcr4D2A:-Mx-4ebzBhioEz6ymqGU:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L281)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`example.`
</blockquote></details>

Done.
___
*[content/blog/2022/async.md, line 322 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzrXuF8Syp2W-Vb2cq:-Mx-4gGS7CD_YkLmtshw:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L322)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

 \```C
</blockquote></details>

Done.
___
*[content/blog/2022/async.md, line 350 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzzVVY0zF_mGhb6tVH:-Mx-5JDfCuZ3y4Ea7tYe:b-g2pzmf) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L350)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

FYI, not sure if that's relevant - you didn't mention `pmemblk` at the beginning
</blockquote></details>

I added a link to a blog post that described pmemblk. 
___
*[content/blog/2022/async.md, line 352 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mx-0QMs2fDUMUEoZ4jt:-Mx-5RmfBvWMjqeQqpRX:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L352)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

these links below are not displayed right now, so this section seems redundant.
</blockquote></details>

Done.

**Review by wlemkows — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/207)* status: all files reviewed, 15 unresolved discussions (waiting on @kswiecicki and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/207)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @kswiecicki, @lukaszstolarczuk, @pbalcer, and @wlemkows)

___
*[content/blog/2022/async.md, line 154 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mwzmn3P2V9-tsB_gq4A:-Mx0-k3L7_fa1KkifJ8w:bqd5jzm) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L154)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I think that would change the meaning of the sentence. I meant that programmers know how to create software that uses async stuff. Not that some arbitrary "software" that is utilized to do async. Po naszemu: "software jest przyzwyczajony do", nie "software jest używany do".
</blockquote></details>

huh... I got to say, I'm not used to using this phrase with inanimate nouns :wink: buuut, maybe it's just me

anyway, you can always update this sentence with what you said - "**programmers** are used to creating software..." - I'll leave it to your judgment.
___
*[content/blog/2022/async.md, line 350 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzzVVY0zF_mGhb6tVH:-Mx02RvnDV5QCqund3KP:b-z1yx0e) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L350)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I added a link to a blog post that described pmemblk. 
</blockquote></details>

Are you sure it's the right link..?
___
*[content/blog/2022/async.md, line 81 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mx00qdX5tUJ-m3ykWpx:-Mx00qdX5tUJ-m3ykWpy:bzih8z2) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a94a7bf67201f356ea1bb4e1bc3c419e116f5ee/content/blog/2022/async.md#L81)):*
> ```Markdown
> specialized instructions, `MOVDIR64B` or `ENQCMD`.
> 
> dma pmem
> ```

all your pics have "dma pmem" given as a text representation (an "alt").
___
*[content/blog/2022/async.md, line 298 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mx01hmdAn6YDZE1qO3H:-Mx01hmdAn6YDZE1qO3I:badoyfi) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a94a7bf67201f356ea1bb4e1bc3c419e116f5ee/content/blog/2022/async.md#L298)):*
> ```Markdown
> some will be satisfied with simpler single-threaded ones. Existing software
> might want to rely on some execution system that it already uses
> (e.g., [an SPDK reactor][[spdk-scheduler]]).
> ```

too many `[]`

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/207)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @kswiecicki, @lukaszstolarczuk, and @wlemkows)

___
*[content/blog/2022/async.md, line 154 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mwzmn3P2V9-tsB_gq4A:-Mx03Rp1Bo5p6oC7jMev:b8hqux) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L154)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

huh... I got to say, I'm not used to using this phrase with inanimate nouns :wink: buuut, maybe it's just me

anyway, you can always update this sentence with what you said - "**programmers** are used to creating software..." - I'll leave it to your judgment.
</blockquote></details>

Changed it to programmers ;P
___
*[content/blog/2022/async.md, line 350 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/207#-MwzzVVY0zF_mGhb6tVH:-Mx03mEgEZLo-yZUc5qX:b-7c5o4) ([raw file](https://github.com/pmem/pmem.github.io/blob/0e639a163416a66576af86900d3f8404af8327e5/content/blog/2022/async.md#L350)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Are you sure it's the right link..?
</blockquote></details>

Yes. It's not about pmemblk per se, but it talks about how it's implemented.
https://pmem.io/blog/2014/09/using-the-block-translation-table-for-sector-atomicity/
___
*[content/blog/2022/async.md, line 81 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mx00qdX5tUJ-m3ykWpx:-Mx0496729G23ZOJkcRX:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a94a7bf67201f356ea1bb4e1bc3c419e116f5ee/content/blog/2022/async.md#L81)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

all your pics have "dma pmem" given as a text representation (an "alt").
</blockquote></details>

Done.
___
*[content/blog/2022/async.md, line 298 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mx01hmdAn6YDZE1qO3H:-Mx03WUb5UcmjfNr6bNJ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a94a7bf67201f356ea1bb4e1bc3c419e116f5ee/content/blog/2022/async.md#L298)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

too many `[]`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/207#-:-Mx05ZU98p2fGjUcR2nF:bnfp4nl)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @kswiecicki, @lukaszstolarczuk, and @wlemkows)

**Comment by kswiecicki** [comment]
___
*[static/images/posts/async-sync-vs-async.png, line 0 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mx3bvx78gW4tT7oNj8J:-Mx3bvx8-sbbTJOOuy4d:b-z3tmvm) ([raw file](https://github.com/pmem/pmem.github.io/blob/c3d501e82882d4dc881938bffeb3ca7697549ffe/static/images/posts/async-sync-vs-async.png#L0)):*
The rectangular shape representing asynchronous write is labelled `wsynchronous`.
It's the `async-sync-vs-async.png` image.

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/207)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @kswiecicki, @lukaszstolarczuk, and @wlemkows)

___
*[static/images/posts/async-sync-vs-async.png, line  at r6](https://reviewable.io/reviews/pmem/pmem.github.io/207#-Mx3bvx78gW4tT7oNj8J:-Mx4h9f65TNDNBcnQ7Fz:bun92oh) ([raw file](https://github.com/pmem/pmem.github.io/blob/c3d501e82882d4dc881938bffeb3ca7697549ffe/static/images/posts/async-sync-vs-async.png#L)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

The rectangular shape representing asynchronous write is labelled `wsynchronous`.
It's the `async-sync-vs-async.png` image.
</blockquote></details>

Done. I also made small updates in other pictures and in the text.

**Pull request merged**
