### PR TITLE
Use release 2.0.0 instead of 1.14.0

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/368)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/368)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`content/pmdk/manpages/linux/v1.13/libpmem/libpmem.7.md` line 33 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/368#-NcaQBRC3duGJoMMjB5f:-NcaPbsf2Pq78rUlMdPB:b-pm9bik) ([raw file](https://github.com/pmem/pmem.github.io/blob/022bcc13af80e0e6f78dd2438992857c078e8292/content/pmdk/manpages/linux/v1.13/libpmem/libpmem.7.md#L33)):*
> ```Markdown
> >NOTE:
> Support for Windows and FreeBSD are deprecated since PMDK 1.13.0 release
> and will be removed in the PMDK 2.0.0 release.
> ```

I believe you should not directly modify files in the `content/pmdk/manpages/` directory.
These are generated from the `pmem/pmdk/doc` manpages and any change you will make by hand will be overwritten by the bot.
___
*[`data/en/pmdk.yml` line 30 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/368#-NcaR6qxCsTnnET6lfvc:-NcaR6qxCsTnnET6lfvd:bmphc5e) ([raw file](https://github.com/pmem/pmem.github.io/blob/022bcc13af80e0e6f78dd2438992857c078e8292/data/en/pmdk.yml#L30)):*
> ```YAML
> 
>     branch_list2:
>       content: "<p>Support for <strong>Windows</strong> and <strong>FreeBSD</strong> are deprecated since <strong>PMDK 1.13.0</strong> release and will be removed in the <strong>PMDK 2.0.0</strong> release.</p>"
> ```

If you will it would be nice to fix articles at least here. I do not want to force you to fix them everywhere else since this change is not about it.



_Suggestion:_
```YAML
      content: "<p>Support for <strong>Windows</strong> and <strong>FreeBSD</strong> is deprecated since the <strong>PMDK 1.13.0</strong> release and was removed in the <strong>PMDK 2.0.0</strong> release.</p>"
```
___
*[`data/en/pmdk.yml` line 45 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/368#-NcaRH062bKZuSU8_CRG:-NcaRH062bKZuSU8_CRH:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/022bcc13af80e0e6f78dd2438992857c078e8292/data/en/pmdk.yml#L45)):*
> ```YAML
>       content: "<p>The <strong>libpmemblk</strong> library supports arrays of pmem-resident blocks, all the same size, that are atomically updated. For example, a program keeping a cache of fixed-size objects in pmem might find this library useful.</p>
>                 <p>See the <a href=\"./libpmemblk\">libpmemblk page</a> for documentation and examples.</p>
>                 <blockquote><p><strong>Note:</strong> The <strong>libpmemblk</strong> library is deprecated since PMDK 1.13.0 release and was removed in the PMDK 2.0.0 release.</p></blockquote>"
> ```





_Suggestion:_
```YAML
                <blockquote><p><strong>Note:</strong> The <strong>libpmemblk</strong> library is deprecated since the PMDK 1.13.0 release and was removed in the PMDK 2.0.0 release.</p></blockquote>"
```
___
*[`data/en/pmdk.yml` line 50 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/368#-NcaRMqx41wYIB0J9isT:-NcaRMqx41wYIB0J9isU:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/022bcc13af80e0e6f78dd2438992857c078e8292/data/en/pmdk.yml#L50)):*
> ```YAML
>       content: "<p>The <strong>libpmemlog</strong> library provides a pmem-resident log file. This is useful for programs like databases that append frequently to a log file.</p>
>                 <p>See the <a href=\"./libpmemlog\">libpmemlog page</a> for documentation and examples.</p>
>                 <blockquote><p><strong>Note:</strong> The <strong>libpmemlog</strong> library is deprecated since PMDK 1.13.0 release and was removed in the PMDK 2.0.0 release.</p></blockquote>"
> ```





_Suggestion:_
```YAML
                <blockquote><p><strong>Note:</strong> The <strong>libpmemlog</strong> library is deprecated since the PMDK 1.13.0 release and was removed in the PMDK 2.0.0 release.</p></blockquote>"
```
___
*[`data/en/pmdk.yml` line 59 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/368#-NcaRS0y7iT0TiFdTGo2:-NcaRS0y7iT0TiFdTGo3:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/022bcc13af80e0e6f78dd2438992857c078e8292/data/en/pmdk.yml#L59)):*
> ```YAML
>       content: "<p>The <strong>libpmem2</strong> library provides low level persistent memory support. The library is a new version of <strong>libpmem</strong>. <strong>libpmem2</strong> provides a more universal and platform-agnostic interface. Developers wishing to roll their own persistent memory algorithms will find this library useful, but most developers will likely use <strong>libpmemobj</strong> above that provides memory allocation and transactions support.</p>
>                 <p>See the <a href=\"./libpmem2\">libpmem2 page</a> for documentation and examples.</p>
>                 <blockquote><p><strong>Note:</strong> Support for async functions is deprecated since PMDK 1.13.0 release and was removed in the PMDK 2.0.0 release along with the miniasync dependency.</p></blockquote>"
> ```





_Suggestion:_
```YAML
                <blockquote><p><strong>Note:</strong> Support for async functions is deprecated since the PMDK 1.13.0 release and was removed in the PMDK 2.0.0 release along with the miniasync dependency.</p></blockquote>"
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/368)* status: 31 of 32 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[`data/en/pmdk.yml` line 30 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/368#-NcaR6qxCsTnnET6lfvc:-Nca_QhL0q9LdtB9ZQpT:bb6un1j) ([raw file](https://github.com/pmem/pmem.github.io/blob/022bcc13af80e0e6f78dd2438992857c078e8292/data/en/pmdk.yml#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If you will it would be nice to fix articles at least here. I do not want to force you to fix them everywhere else since this change is not about it.
</blockquote></details>

Done
___
*[`data/en/pmdk.yml` line 45 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/368#-NcaRH062bKZuSU8_CRG:-Nca_OLn8Lba2ftOwkvQ:bb6un1j) ([raw file](https://github.com/pmem/pmem.github.io/blob/022bcc13af80e0e6f78dd2438992857c078e8292/data/en/pmdk.yml#L45)):*
> ```YAML
>       content: "<p>The <strong>libpmemblk</strong> library supports arrays of pmem-resident blocks, all the same size, that are atomically updated. For example, a program keeping a cache of fixed-size objects in pmem might find this library useful.</p>
>                 <p>See the <a href=\"./libpmemblk\">libpmemblk page</a> for documentation and examples.</p>
>                 <blockquote><p><strong>Note:</strong> The <strong>libpmemblk</strong> library is deprecated since PMDK 1.13.0 release and was removed in the PMDK 2.0.0 release.</p></blockquote>"
> ```

Done
___
*[`data/en/pmdk.yml` line 50 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/368#-NcaRMqx41wYIB0J9isT:-Nca_C4N42LoAINs4kOJ:bb6un1j) ([raw file](https://github.com/pmem/pmem.github.io/blob/022bcc13af80e0e6f78dd2438992857c078e8292/data/en/pmdk.yml#L50)):*
> ```YAML
>       content: "<p>The <strong>libpmemlog</strong> library provides a pmem-resident log file. This is useful for programs like databases that append frequently to a log file.</p>
>                 <p>See the <a href=\"./libpmemlog\">libpmemlog page</a> for documentation and examples.</p>
>                 <blockquote><p><strong>Note:</strong> The <strong>libpmemlog</strong> library is deprecated since PMDK 1.13.0 release and was removed in the PMDK 2.0.0 release.</p></blockquote>"
> ```

Done
___
*[`data/en/pmdk.yml` line 59 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/368#-NcaRS0y7iT0TiFdTGo2:-Nca_6px76ACVc6Spg3l:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/022bcc13af80e0e6f78dd2438992857c078e8292/data/en/pmdk.yml#L59)):*
> ```YAML
>       content: "<p>The <strong>libpmem2</strong> library provides low level persistent memory support. The library is a new version of <strong>libpmem</strong>. <strong>libpmem2</strong> provides a more universal and platform-agnostic interface. Developers wishing to roll their own persistent memory algorithms will find this library useful, but most developers will likely use <strong>libpmemobj</strong> above that provides memory allocation and transactions support.</p>
>                 <p>See the <a href=\"./libpmem2\">libpmem2 page</a> for documentation and examples.</p>
>                 <blockquote><p><strong>Note:</strong> Support for async functions is deprecated since PMDK 1.13.0 release and was removed in the PMDK 2.0.0 release along with the miniasync dependency.</p></blockquote>"
> ```

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/368)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`data/en/pmdk.yml` line 30 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/368#-Ncb4dEk9r71ZmwgwiTs:-Ncb4dEk9r71ZmwgwiTt:undefined) ([raw file](https://github.com/pmem/pmem.github.io/blob/4d8106e5f5b3e49be36040614a6ea32aaaf3abbf/data/en/pmdk.yml#L30)):*
> ```YAML
> 
>     branch_list2:
>       content: "<p>Support for <strong>Windows</strong> and <strong>FreeBSD</strong> is deprecated since the <strong>PMDK 1.13.0</strong> release and will be removed in the <strong>PMDK 2.0.0</strong> release.</p>"
> ```





_Suggestion:_
```YAML
and was removed in the
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/368)* status: 31 of 32 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[`data/en/pmdk.yml` line 30 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/368#-Ncb4dEk9r71ZmwgwiTs:-NcbP-qYCmoxdw87luuM:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/4d8106e5f5b3e49be36040614a6ea32aaaf3abbf/data/en/pmdk.yml#L30)):*
> ```YAML
> 
>     branch_list2:
>       content: "<p>Support for <strong>Windows</strong> and <strong>FreeBSD</strong> is deprecated since the <strong>PMDK 1.13.0</strong> release and will be removed in the <strong>PMDK 2.0.0</strong> release.</p>"
> ```

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/368#-:-NcbdbzyCI4W2y571Te0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/368)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[`content/pmdk/manpages/linux/v1.13/libpmem/libpmem.7.md` line 33 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/368#-NcaQBRC3duGJoMMjB5f:-Ncbd_F67QpJgV0lyqNF:b8rsao6) ([raw file](https://github.com/pmem/pmem.github.io/blob/022bcc13af80e0e6f78dd2438992857c078e8292/content/pmdk/manpages/linux/v1.13/libpmem/libpmem.7.md#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I believe you should not directly modify files in the `content/pmdk/manpages/` directory.
These are generated from the `pmem/pmdk/doc` manpages and any change you will make by hand will be overwritten by the bot.
</blockquote></details>

Also changed in pmem/pmdk@stable-1.13
https://github.com/pmem/pmdk/pull/5875

**Pull request merged**
