### PR TITLE
Add SNIA Persistent Memory and Computational Storage Summit 2022 Event

### PR DESCRIPTION
**Pull request by sscargal**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/211)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/211)* status: all files reviewed, 1 unresolved discussion (waiting on @sscargal)

___
*[content/events/2022-SNIA-Persistent-Memory-Summit.md, line 7 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/211#-MxAxifu7ROJ_V-WBe9p:-MxAxifu7ROJ_V-WBe9q:b-9nochp) ([raw file](https://github.com/pmem/pmem.github.io/blob/d766e6778b58d305394b61922b101fae274af8c7/content/events/2022-SNIA-Persistent-Memory-Summit.md#L7)):*
> ```Markdown
> # Publish date
> date: '2022-03-02T00:00:00Z'
> ```

not sure if needed, missing `draft: false` (?)

**Comment by sscargal** [comment]
`draft: false` is the default, so it's not technically required. I/We put it in the original template so we could test draft vs non-draft.

**Review by sscargal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/211)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[content/events/2022-SNIA-Persistent-Memory-Summit.md, line 7 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/211#-MxAxifu7ROJ_V-WBe9p:-MxB0bhx7cWS2rwqW_gJ:b-21vva8) ([raw file](https://github.com/pmem/pmem.github.io/blob/d766e6778b58d305394b61922b101fae274af8c7/content/events/2022-SNIA-Persistent-Memory-Summit.md#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not sure if needed, missing `draft: false` (?)
</blockquote></details>

`draft: false` is the default, so it's not technically required.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/211#-:-MxDqUyR8JCfczyfvs_i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sscargal)

**Pull request merged**
